// Code generated by ent, DO NOT EDIT.

package admindatapermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldTenantID, v))
}

// AdminID applies equality check predicate on the "admin_id" field. It's identical to AdminIDEQ.
func AdminID(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldAdminID, v))
}

// DataPermissionID applies equality check predicate on the "data_permission_id" field. It's identical to DataPermissionIDEQ.
func DataPermissionID(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldDataPermissionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContainsFold(FieldTenantID, v))
}

// AdminIDEQ applies the EQ predicate on the "admin_id" field.
func AdminIDEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldAdminID, v))
}

// AdminIDNEQ applies the NEQ predicate on the "admin_id" field.
func AdminIDNEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNEQ(FieldAdminID, v))
}

// AdminIDIn applies the In predicate on the "admin_id" field.
func AdminIDIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldIn(FieldAdminID, vs...))
}

// AdminIDNotIn applies the NotIn predicate on the "admin_id" field.
func AdminIDNotIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNotIn(FieldAdminID, vs...))
}

// AdminIDGT applies the GT predicate on the "admin_id" field.
func AdminIDGT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGT(FieldAdminID, v))
}

// AdminIDGTE applies the GTE predicate on the "admin_id" field.
func AdminIDGTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGTE(FieldAdminID, v))
}

// AdminIDLT applies the LT predicate on the "admin_id" field.
func AdminIDLT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLT(FieldAdminID, v))
}

// AdminIDLTE applies the LTE predicate on the "admin_id" field.
func AdminIDLTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLTE(FieldAdminID, v))
}

// AdminIDContains applies the Contains predicate on the "admin_id" field.
func AdminIDContains(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContains(FieldAdminID, v))
}

// AdminIDHasPrefix applies the HasPrefix predicate on the "admin_id" field.
func AdminIDHasPrefix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasPrefix(FieldAdminID, v))
}

// AdminIDHasSuffix applies the HasSuffix predicate on the "admin_id" field.
func AdminIDHasSuffix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasSuffix(FieldAdminID, v))
}

// AdminIDEqualFold applies the EqualFold predicate on the "admin_id" field.
func AdminIDEqualFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEqualFold(FieldAdminID, v))
}

// AdminIDContainsFold applies the ContainsFold predicate on the "admin_id" field.
func AdminIDContainsFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContainsFold(FieldAdminID, v))
}

// DataPermissionIDEQ applies the EQ predicate on the "data_permission_id" field.
func DataPermissionIDEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldDataPermissionID, v))
}

// DataPermissionIDNEQ applies the NEQ predicate on the "data_permission_id" field.
func DataPermissionIDNEQ(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNEQ(FieldDataPermissionID, v))
}

// DataPermissionIDIn applies the In predicate on the "data_permission_id" field.
func DataPermissionIDIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldIn(FieldDataPermissionID, vs...))
}

// DataPermissionIDNotIn applies the NotIn predicate on the "data_permission_id" field.
func DataPermissionIDNotIn(vs ...string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNotIn(FieldDataPermissionID, vs...))
}

// DataPermissionIDGT applies the GT predicate on the "data_permission_id" field.
func DataPermissionIDGT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGT(FieldDataPermissionID, v))
}

// DataPermissionIDGTE applies the GTE predicate on the "data_permission_id" field.
func DataPermissionIDGTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGTE(FieldDataPermissionID, v))
}

// DataPermissionIDLT applies the LT predicate on the "data_permission_id" field.
func DataPermissionIDLT(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLT(FieldDataPermissionID, v))
}

// DataPermissionIDLTE applies the LTE predicate on the "data_permission_id" field.
func DataPermissionIDLTE(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLTE(FieldDataPermissionID, v))
}

// DataPermissionIDContains applies the Contains predicate on the "data_permission_id" field.
func DataPermissionIDContains(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContains(FieldDataPermissionID, v))
}

// DataPermissionIDHasPrefix applies the HasPrefix predicate on the "data_permission_id" field.
func DataPermissionIDHasPrefix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasPrefix(FieldDataPermissionID, v))
}

// DataPermissionIDHasSuffix applies the HasSuffix predicate on the "data_permission_id" field.
func DataPermissionIDHasSuffix(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldHasSuffix(FieldDataPermissionID, v))
}

// DataPermissionIDEqualFold applies the EqualFold predicate on the "data_permission_id" field.
func DataPermissionIDEqualFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEqualFold(FieldDataPermissionID, v))
}

// DataPermissionIDContainsFold applies the ContainsFold predicate on the "data_permission_id" field.
func DataPermissionIDContainsFold(v string) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldContainsFold(FieldDataPermissionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAdmin applies the HasEdge predicate on the "admin" edge.
func HasAdmin() predicate.AdminDataPermission {
	return predicate.AdminDataPermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AdminTable, AdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdminWith applies the HasEdge predicate on the "admin" edge with a given conditions (other predicates).
func HasAdminWith(preds ...predicate.Admin) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(func(s *sql.Selector) {
		step := newAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDataPermission applies the HasEdge predicate on the "data_permission" edge.
func HasDataPermission() predicate.AdminDataPermission {
	return predicate.AdminDataPermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DataPermissionTable, DataPermissionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDataPermissionWith applies the HasEdge predicate on the "data_permission" edge with a given conditions (other predicates).
func HasDataPermissionWith(preds ...predicate.DataPermission) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(func(s *sql.Selector) {
		step := newDataPermissionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminDataPermission) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminDataPermission) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminDataPermission) predicate.AdminDataPermission {
	return predicate.AdminDataPermission(sql.NotPredicates(p))
}
