// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/antsurge/weaver-admin/app/admin/service/internal/biz"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/conf"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/handler"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/server"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, app *conf.App, mq *conf.MQ, openAPI *conf.OpenAPI, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEntClient(confData, logger)
	redisClient := data.NewRedisClient(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, client, redisClient)
	if err != nil {
		return nil, nil, err
	}
	adminRepo := data.NewAdminRepo(dataData, logger)
	captchaRepo := data.NewCaptchaRepo(dataData, logger, confData)
	tokenRepo := data.NewTokenRepo(dataData, logger, confData)
	roleRepo := data.NewRoleRepo(dataData, logger)
	apiPermissionRepo := data.NewApiPermissionRepo(dataData, logger)
	menuRepo := data.NewMenuRepo(dataData, logger, apiPermissionRepo)
	adminRoleRepo := data.NewAdminRoleRepo(dataData, logger)
	roleMenuRepo := data.NewRoleMenuRepo(dataData, logger)
	authenticationUsecase := biz.NewAuthenticationUsecase(logger, adminRepo, captchaRepo, tokenRepo, roleRepo, menuRepo, adminRoleRepo, roleMenuRepo, jwt, app)
	captchaUsecase := biz.NewCaptchaUsecase(captchaRepo, logger)
	authenticationService := service.NewAuthenticationService(authenticationUsecase, captchaUsecase)
	menuUsecase := biz.NewMenuUsecase(menuRepo, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, menuRepo, logger)
	openapi_scannerService := data.NewOpenAPIScanner(openAPI, logger)
	permissionService := service.NewPermissionService(menuUsecase, roleUsecase, openapi_scannerService)
	departmentRepo := data.NewDepartmentRepo(dataData, logger)
	departmentUsecase := biz.NewDepartmentUsecase(departmentRepo, logger)
	positionRepo := data.NewPositionRepo(dataData, logger)
	positionUsecase := biz.NewPositionUsecase(positionRepo, logger)
	organizationService := service.NewOrganizationService(departmentUsecase, positionUsecase)
	dictTypeRepo := data.NewDictTypeRepo(dataData, logger)
	dictDataRepo := data.NewDictDataRepo(dataData, logger)
	dictTypeUsecase := biz.NewDictTypeUsecase(dictTypeRepo, dictDataRepo, logger)
	dictDataUsecase := biz.NewDictDataUsecase(dictDataRepo, logger)
	dictionaryService := service.NewDictionaryService(dictTypeUsecase, dictDataUsecase)
	adminUseCase := biz.NewAdminUseCase(adminRepo, roleRepo, logger)
	identityService := service.NewIdentityService(adminUseCase)
	apiInterfaceRepo := data.NewApiInterfaceRepo(dataData, logger)
	apiInterfaceUsecase := biz.NewApiInterfaceUsecase(apiInterfaceRepo, logger)
	systemService := service.NewSystemService(apiInterfaceUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, authenticationService, permissionService, organizationService, dictionaryService, identityService, systemService, logger)
	organizationHandler := handler.NewOrganizationHandler(positionUsecase)
	systemHandler := handler.NewSystemHandler(apiInterfaceUsecase)
	httpServer := server.NewHTTPServer(confServer, jwt, app, authenticationService, permissionService, organizationService, dictionaryService, identityService, systemService, organizationHandler, systemHandler, logger)
	kratosApp := newApp(logger, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
