// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/antsurge/weaver-admin/app/admin/service/internal/biz"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/conf"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/handler"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/server"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, app *conf.App, openAPI *conf.OpenAPI, oss *conf.OSS, mq *conf.MQ, codegen *conf.Codegen, logger log.Logger) (*kratos.App, func(), error) {
	entDriver, cleanup, err := data.NewEntDriver(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewEntClient(entDriver, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db := data.NewSQLDB(entDriver)
	redisClient := data.NewRedisClient(confData, logger)
	dataData, cleanup2, err := data.NewData(confData, logger, client, db, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationRepo := data.NewNotificationRepo(dataData, logger)
	broker, cleanup3, err := data.NewMessageBroker(mq, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationHub := biz.NewNotificationHub()
	notificationUsecase := biz.NewNotificationUsecase(notificationRepo, broker, notificationHub, logger)
	mqServer := server.NewMQServer(notificationUsecase, logger)
	logRepo := data.NewLogRepo(dataData, logger)
	operationLogRecorder := biz.NewOperationLogRecorder(logRepo, logger)
	logRecorderServer := server.NewLogRecorderServer(operationLogRecorder, logger)
	cronJobRepo := data.NewCronJobRepo(dataData, logger)
	jobLocker := data.NewRedisJobLocker(dataData)
	httpExecutor := biz.NewHTTPExecutor()
	jobScheduler := biz.NewJobScheduler(cronJobRepo, jobLocker, httpExecutor)
	jobSchedulerServer := server.NewJobSchedulerServer(jobScheduler, logger)
	transportServer := server.NewBackgroundServer(mqServer, logRecorderServer, jobSchedulerServer)
	tokenRepo := data.NewTokenRepo(dataData, logger, confData)
	adminRepo := data.NewAdminRepo(dataData, logger)
	captchaRepo := data.NewCaptchaRepo(dataData, logger, confData)
	roleRepo := data.NewRoleRepo(dataData, logger)
	menuRepo := data.NewMenuRepo(dataData, logger)
	adminRoleRepo := data.NewAdminRoleRepo(dataData, logger)
	roleMenuRepo := data.NewRoleMenuRepo(dataData, logger)
	logUsecase := biz.NewLogUsecase(logRepo, adminRepo, logger)
	securityRepo := data.NewSecurityRepo(dataData, logger, confData)
	securityUsecase := biz.NewSecurityUsecase(securityRepo, logger)
	tenantRepo := data.NewTenantRepo(dataData, logger)
	authenticationUsecase := biz.NewAuthenticationUsecase(logger, adminRepo, captchaRepo, tokenRepo, roleRepo, menuRepo, adminRoleRepo, roleMenuRepo, logUsecase, jwt, app, securityUsecase, tenantRepo)
	captchaUsecase := biz.NewCaptchaUsecase(captchaRepo, logger)
	authenticationService := service.NewAuthenticationService(authenticationUsecase, captchaUsecase)
	menuUsecase := biz.NewMenuUsecase(menuRepo, logger)
	tenantUsecase := biz.NewTenantUsecase(tenantRepo, logger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, menuRepo, tenantUsecase, app, logger)
	openapi_scannerService := data.NewOpenAPIScanner(openAPI, logger)
	dataPermissionRepo := data.NewDataPermissionRepo(dataData, logger)
	dataPermissionUsecase := biz.NewDataPermissionUsecase(dataPermissionRepo, logger)
	permissionService := service.NewPermissionService(menuUsecase, roleUsecase, openapi_scannerService, dataPermissionUsecase)
	departmentRepo := data.NewDepartmentRepo(dataData, logger)
	departmentUsecase := biz.NewDepartmentUsecase(departmentRepo, logger)
	positionRepo := data.NewPositionRepo(dataData, logger)
	positionUsecase := biz.NewPositionUsecase(positionRepo, logger)
	organizationService := service.NewOrganizationService(departmentUsecase, positionUsecase)
	tenantService := service.NewTenantService(tenantUsecase)
	adminUseCase := biz.NewAdminUseCase(adminRepo, roleRepo, tenantUsecase, app, logger)
	storage := data.NewObjectStorage(oss, logger)
	objectStorage := data.NewObjectStorageProvider(storage)
	fileUsecase := biz.NewFileUsecase(objectStorage, oss, logger)
	identityService := service.NewIdentityService(adminUseCase, fileUsecase)
	apiInterfaceRepo := data.NewApiInterfaceRepo(dataData, logger)
	apiInterfaceUsecase := biz.NewApiInterfaceUsecase(apiInterfaceRepo, logger)
	dictTypeRepo := data.NewDictTypeRepo(dataData, logger)
	dictDataRepo := data.NewDictDataRepo(dataData, logger)
	dictTypeUsecase := biz.NewDictTypeUsecase(dictTypeRepo, dictDataRepo, logger)
	dictDataUsecase := biz.NewDictDataUsecase(dictDataRepo, logger)
	configRepo := data.NewConfigRepo(dataData, logger)
	configUsecase := biz.NewConfigUsecase(configRepo, logger)
	systemService := service.NewSystemService(apiInterfaceUsecase, dictTypeUsecase, dictDataUsecase, configUsecase, logger)
	fileService := service.NewFileService(fileUsecase, logger)
	messageService := service.NewMessageService(notificationUsecase, logger)
	onlineUsecase := biz.NewOnlineUsecase(logger, tokenRepo, adminRepo)
	securityService := service.NewSecurityService(securityUsecase, onlineUsecase, logUsecase, logger)
	cronjobUsecase := biz.NewCronjobUsecase(cronJobRepo, jobScheduler, logger)
	monitorRepo := data.NewMonitorRepo(dataData, logger)
	collector := biz.NewApiMetricsCollector()
	monitorUsecase := biz.NewMonitorUsecase(monitorRepo, collector, jobScheduler, logger)
	opsService := service.NewOpsService(cronjobUsecase, monitorUsecase)
	formSchemaRepo := data.NewFormSchemaRepo(dataData, logger)
	formSchemaUsecase := biz.NewFormSchemaUsecase(formSchemaRepo, logger)
	formSubmissionRepo := data.NewFormSubmissionRepo(dataData, logger)
	formSubmissionUsecase := biz.NewFormSubmissionUsecase(formSubmissionRepo, formSchemaRepo, logger)
	genTableRepo := data.NewGenTableRepo(dataData, logger)
	dbMetadataRepo := data.NewDbMetadataRepo(dataData, logger)
	codegenUsecase := biz.NewCodegenUsecase(genTableRepo, dbMetadataRepo, codegen, logger)
	lowcodeService := service.NewLowcodeService(formSchemaUsecase, formSubmissionUsecase, codegenUsecase)
	grpcServer := server.NewGRPCServer(confServer, jwt, tokenRepo, authenticationService, permissionService, organizationService, tenantService, identityService, systemService, fileService, messageService, securityService, opsService, lowcodeService, operationLogRecorder, openapi_scannerService, logger)
	authzRepo := data.NewAuthzRepo(dataData, logger)
	authzCache := data.NewAuthzCache(dataData, logger, confData)
	authzUseCase := biz.NewAuthzUseCase(authzRepo, authzCache, app, logger)
	organizationHandler := handler.NewOrganizationHandler(positionUsecase, departmentUsecase)
	systemHandler := handler.NewSystemHandler(apiInterfaceUsecase)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	fileHandler := handler.NewFileHandler(fileUsecase)
	notificationHandler := handler.NewNotificationHandler(notificationUsecase, notificationHub)
	codegenHandler := handler.NewCodegenHandler(codegenUsecase, menuUsecase, logger)
	profileHandler := handler.NewProfileHandler(adminUseCase)
	httpServer := server.NewHTTPServer(confServer, jwt, app, tokenRepo, authzUseCase, securityUsecase, tenantUsecase, collector, authenticationService, permissionService, organizationService, tenantService, identityService, systemService, fileService, messageService, opsService, securityService, lowcodeService, operationLogRecorder, openapi_scannerService, organizationHandler, systemHandler, adminHandler, fileHandler, notificationHandler, codegenHandler, profileHandler, logger)
	kratosApp := newApp(logger, transportServer, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
