import type { CodegenApi } from '#/api/lowcode/codegen';

/** 画布上的字段项（在 GenField 基础上增加唯一 key 与默认列名生成序号） */
export interface FieldItem extends CodegenApi.GenField {
  /** 画布内唯一 key */
  key: string;
}

/** 字段库分组：常用 / 基础 / 高级 */
export const FIELD_LIB: {
  fields: {
    /** 显示名称 */
    label: string;
    /** 默认配置模板 */
    template: {
      /** 列名前缀（自动去重：首个不加后缀，重复时追加 _01、_02…），空表示需要手动填列名 */
      colPrefix: string;
    } & Omit<FieldItem, 'columnName' | 'fieldName' | 'key'>;
    /** 字段类型标识（组件类型） */
    type: string;
  }[];
  group: string;
  i18nKey: string;
}[] = [
  {
    group: 'common',
    i18nKey: 'lowcode.codegen.designer.fieldLib.common',
    fields: [
      {
        type: 'PrimaryKey',
        label: '主键',
        template: {
          colPrefix: 'id',
          columnComment: 'ID',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: true,
          list: false,
          form: false,
          query: false,
          required: false,
        },
      },
      {
        type: 'PrimaryKeySnowflake',
        label: '主键（雪花ID）',
        template: {
          colPrefix: 'id',
          columnComment: 'ID',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: true,
          list: false,
          form: false,
          query: false,
          required: false,
        },
      },
      {
        type: 'Status',
        label: '状态',
        template: {
          colPrefix: 'status',
          columnComment: '状态',
          goType: 'int64',
          componentType: 'Select',
          length: 4,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Remark',
        label: '备注',
        template: {
          colPrefix: 'remark',
          columnComment: '备注',
          goType: 'string',
          componentType: 'Textarea',
          length: 500,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Weight',
        label: '权重（拖拽排序）',
        template: {
          colPrefix: 'weight',
          columnComment: '权重',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'UpdatedAt',
        label: '修改时间',
        template: {
          colPrefix: 'updated_at',
          columnComment: '修改时间',
          goType: 'time.Time',
          componentType: 'DatePicker',
          length: 0,
          primaryKey: false,
          list: true,
          form: false,
          query: false,
          required: false,
        },
      },
      {
        type: 'CreatedAt',
        label: '创建时间',
        template: {
          colPrefix: 'created_at',
          columnComment: '创建时间',
          goType: 'time.Time',
          componentType: 'DatePicker',
          length: 0,
          primaryKey: false,
          list: true,
          form: false,
          query: false,
          required: false,
        },
      },
      {
        type: 'RemoteSelect',
        label: '远程下拉（关联表）',
        template: {
          colPrefix: 'xxx_id',
          columnComment: '远程下拉',
          goType: 'int64',
          componentType: 'Select',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
    ],
  },
  {
    group: 'basic',
    i18nKey: 'lowcode.codegen.designer.fieldLib.basic',
    fields: [
      {
        type: 'Input',
        label: '字符串',
        template: {
          colPrefix: 'name',
          columnComment: '名称',
          goType: 'string',
          componentType: 'Input',
          length: 255,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Image',
        label: '图片',
        template: {
          colPrefix: 'image',
          columnComment: '图片',
          goType: 'string',
          componentType: 'Input',
          length: 255,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'File',
        label: '文件',
        template: {
          colPrefix: 'file',
          columnComment: '文件',
          goType: 'string',
          componentType: 'Input',
          length: 255,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Radio',
        label: '单选框',
        template: {
          colPrefix: 'radio',
          columnComment: '单选',
          goType: 'string',
          componentType: 'Radio',
          length: 50,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Checkbox',
        label: '复选框',
        template: {
          colPrefix: 'checkbox',
          columnComment: '复选',
          goType: 'string',
          componentType: 'Checkbox',
          length: 255,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Select',
        label: '下拉框',
        template: {
          colPrefix: 'select',
          columnComment: '下拉选择',
          goType: 'string',
          componentType: 'Select',
          length: 50,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Switch',
        label: '开关',
        template: {
          colPrefix: 'switch',
          columnComment: '开关',
          goType: 'bool',
          componentType: 'Switch',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'RichText',
        label: '富文本',
        template: {
          colPrefix: 'content',
          columnComment: '内容',
          goType: 'string',
          componentType: 'Textarea',
          length: 0,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Textarea',
        label: '多行文本框',
        template: {
          colPrefix: 'remark',
          columnComment: '备注',
          goType: 'string',
          componentType: 'Textarea',
          length: 500,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'InputNumber',
        label: '数字',
        template: {
          colPrefix: 'number',
          columnComment: '数字',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Float',
        label: '浮点数',
        template: {
          colPrefix: 'float_num',
          columnComment: '浮点数',
          goType: 'float64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Password',
        label: '密码',
        template: {
          colPrefix: 'password',
          columnComment: '密码',
          goType: 'string',
          componentType: 'Input',
          length: 128,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'Date',
        label: '日期',
        template: {
          colPrefix: 'date',
          columnComment: '日期',
          goType: 'time.Time',
          componentType: 'DatePicker',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Time',
        label: '时间',
        template: {
          colPrefix: 'time',
          columnComment: '时间',
          goType: 'time.Time',
          componentType: 'DatePicker',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'DateTime',
        label: '时间日期',
        template: {
          colPrefix: 'datetime',
          columnComment: '时间日期',
          goType: 'time.Time',
          componentType: 'DatePicker',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Year',
        label: '年份',
        template: {
          colPrefix: 'year',
          columnComment: '年份',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'Timestamp',
        label: '时间日期（时间戳存储）',
        template: {
          colPrefix: 'timestamp',
          columnComment: '时间戳',
          goType: 'int64',
          componentType: 'InputNumber',
          length: 0,
          primaryKey: false,
          list: true,
          form: false,
          query: false,
          required: false,
        },
      },
    ],
  },
  {
    group: 'advanced',
    i18nKey: 'lowcode.codegen.designer.fieldLib.advanced',
    fields: [
      {
        type: 'Array',
        label: '数组',
        template: {
          colPrefix: 'items',
          columnComment: '数组',
          goType: 'string',
          componentType: 'Input',
          length: 0,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'CitySelect',
        label: '城市选择',
        template: {
          colPrefix: 'city',
          columnComment: '城市',
          goType: 'string',
          componentType: 'Select',
          length: 100,
          primaryKey: false,
          list: true,
          form: true,
          query: true,
          required: false,
        },
      },
      {
        type: 'IconSelect',
        label: '图标选择',
        template: {
          colPrefix: 'icon',
          columnComment: '图标',
          goType: 'string',
          componentType: 'Input',
          length: 100,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'ColorPicker',
        label: '颜色选择器',
        template: {
          colPrefix: 'color',
          columnComment: '颜色',
          goType: 'string',
          componentType: 'Input',
          length: 50,
          primaryKey: false,
          list: true,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'ImageMultiple',
        label: '图片（多选）',
        template: {
          colPrefix: 'images',
          columnComment: '图片',
          goType: 'string',
          componentType: 'Input',
          length: 1000,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'FileMultiple',
        label: '文件（多选）',
        template: {
          colPrefix: 'files',
          columnComment: '文件',
          goType: 'string',
          componentType: 'Input',
          length: 1000,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'SelectMultiple',
        label: '下拉框（多选）',
        template: {
          colPrefix: 'categories',
          columnComment: '多选',
          goType: 'string',
          componentType: 'Select',
          length: 255,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
      {
        type: 'RemoteSelectMultiple',
        label: '远程下拉（关联多选）',
        template: {
          colPrefix: 'xxx_ids',
          columnComment: '关联多选',
          goType: 'string',
          componentType: 'Select',
          length: 0,
          primaryKey: false,
          list: false,
          form: true,
          query: false,
          required: false,
        },
      },
    ],
  },
];

/** 画布拖动时使用的 dataTransfer 类型键 */
export const DRAG_MIME = 'application/x-codegen-field-type';
