// Code generated by ent, DO NOT EDIT.

package sysjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldName, v))
}

// JobGroup applies equality check predicate on the "job_group" field. It's identical to JobGroupEQ.
func JobGroup(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldJobGroup, v))
}

// JobType applies equality check predicate on the "job_type" field. It's identical to JobTypeEQ.
func JobType(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldJobType, v))
}

// InvokeTarget applies equality check predicate on the "invoke_target" field. It's identical to InvokeTargetEQ.
func InvokeTarget(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldInvokeTarget, v))
}

// CronExpression applies equality check predicate on the "cron_expression" field. It's identical to CronExpressionEQ.
func CronExpression(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCronExpression, v))
}

// MisfirePolicy applies equality check predicate on the "misfire_policy" field. It's identical to MisfirePolicyEQ.
func MisfirePolicy(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldMisfirePolicy, v))
}

// Concurrent applies equality check predicate on the "concurrent" field. It's identical to ConcurrentEQ.
func Concurrent(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldConcurrent, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRemark, v))
}

// NextRunTime applies equality check predicate on the "next_run_time" field. It's identical to NextRunTimeEQ.
func NextRunTime(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldNextRunTime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldName, v))
}

// JobGroupEQ applies the EQ predicate on the "job_group" field.
func JobGroupEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldJobGroup, v))
}

// JobGroupNEQ applies the NEQ predicate on the "job_group" field.
func JobGroupNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldJobGroup, v))
}

// JobGroupIn applies the In predicate on the "job_group" field.
func JobGroupIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldJobGroup, vs...))
}

// JobGroupNotIn applies the NotIn predicate on the "job_group" field.
func JobGroupNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldJobGroup, vs...))
}

// JobGroupGT applies the GT predicate on the "job_group" field.
func JobGroupGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldJobGroup, v))
}

// JobGroupGTE applies the GTE predicate on the "job_group" field.
func JobGroupGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldJobGroup, v))
}

// JobGroupLT applies the LT predicate on the "job_group" field.
func JobGroupLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldJobGroup, v))
}

// JobGroupLTE applies the LTE predicate on the "job_group" field.
func JobGroupLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldJobGroup, v))
}

// JobGroupContains applies the Contains predicate on the "job_group" field.
func JobGroupContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldJobGroup, v))
}

// JobGroupHasPrefix applies the HasPrefix predicate on the "job_group" field.
func JobGroupHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldJobGroup, v))
}

// JobGroupHasSuffix applies the HasSuffix predicate on the "job_group" field.
func JobGroupHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldJobGroup, v))
}

// JobGroupEqualFold applies the EqualFold predicate on the "job_group" field.
func JobGroupEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldJobGroup, v))
}

// JobGroupContainsFold applies the ContainsFold predicate on the "job_group" field.
func JobGroupContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldJobGroup, v))
}

// JobTypeEQ applies the EQ predicate on the "job_type" field.
func JobTypeEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldJobType, v))
}

// JobTypeNEQ applies the NEQ predicate on the "job_type" field.
func JobTypeNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldJobType, v))
}

// JobTypeIn applies the In predicate on the "job_type" field.
func JobTypeIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldJobType, vs...))
}

// JobTypeNotIn applies the NotIn predicate on the "job_type" field.
func JobTypeNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldJobType, vs...))
}

// JobTypeGT applies the GT predicate on the "job_type" field.
func JobTypeGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldJobType, v))
}

// JobTypeGTE applies the GTE predicate on the "job_type" field.
func JobTypeGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldJobType, v))
}

// JobTypeLT applies the LT predicate on the "job_type" field.
func JobTypeLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldJobType, v))
}

// JobTypeLTE applies the LTE predicate on the "job_type" field.
func JobTypeLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldJobType, v))
}

// JobTypeContains applies the Contains predicate on the "job_type" field.
func JobTypeContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldJobType, v))
}

// JobTypeHasPrefix applies the HasPrefix predicate on the "job_type" field.
func JobTypeHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldJobType, v))
}

// JobTypeHasSuffix applies the HasSuffix predicate on the "job_type" field.
func JobTypeHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldJobType, v))
}

// JobTypeEqualFold applies the EqualFold predicate on the "job_type" field.
func JobTypeEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldJobType, v))
}

// JobTypeContainsFold applies the ContainsFold predicate on the "job_type" field.
func JobTypeContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldJobType, v))
}

// InvokeTargetEQ applies the EQ predicate on the "invoke_target" field.
func InvokeTargetEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldInvokeTarget, v))
}

// InvokeTargetNEQ applies the NEQ predicate on the "invoke_target" field.
func InvokeTargetNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldInvokeTarget, v))
}

// InvokeTargetIn applies the In predicate on the "invoke_target" field.
func InvokeTargetIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldInvokeTarget, vs...))
}

// InvokeTargetNotIn applies the NotIn predicate on the "invoke_target" field.
func InvokeTargetNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldInvokeTarget, vs...))
}

// InvokeTargetGT applies the GT predicate on the "invoke_target" field.
func InvokeTargetGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldInvokeTarget, v))
}

// InvokeTargetGTE applies the GTE predicate on the "invoke_target" field.
func InvokeTargetGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldInvokeTarget, v))
}

// InvokeTargetLT applies the LT predicate on the "invoke_target" field.
func InvokeTargetLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldInvokeTarget, v))
}

// InvokeTargetLTE applies the LTE predicate on the "invoke_target" field.
func InvokeTargetLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldInvokeTarget, v))
}

// InvokeTargetContains applies the Contains predicate on the "invoke_target" field.
func InvokeTargetContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldInvokeTarget, v))
}

// InvokeTargetHasPrefix applies the HasPrefix predicate on the "invoke_target" field.
func InvokeTargetHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldInvokeTarget, v))
}

// InvokeTargetHasSuffix applies the HasSuffix predicate on the "invoke_target" field.
func InvokeTargetHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldInvokeTarget, v))
}

// InvokeTargetEqualFold applies the EqualFold predicate on the "invoke_target" field.
func InvokeTargetEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldInvokeTarget, v))
}

// InvokeTargetContainsFold applies the ContainsFold predicate on the "invoke_target" field.
func InvokeTargetContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldInvokeTarget, v))
}

// CronExpressionEQ applies the EQ predicate on the "cron_expression" field.
func CronExpressionEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCronExpression, v))
}

// CronExpressionNEQ applies the NEQ predicate on the "cron_expression" field.
func CronExpressionNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCronExpression, v))
}

// CronExpressionIn applies the In predicate on the "cron_expression" field.
func CronExpressionIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCronExpression, vs...))
}

// CronExpressionNotIn applies the NotIn predicate on the "cron_expression" field.
func CronExpressionNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCronExpression, vs...))
}

// CronExpressionGT applies the GT predicate on the "cron_expression" field.
func CronExpressionGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCronExpression, v))
}

// CronExpressionGTE applies the GTE predicate on the "cron_expression" field.
func CronExpressionGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCronExpression, v))
}

// CronExpressionLT applies the LT predicate on the "cron_expression" field.
func CronExpressionLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCronExpression, v))
}

// CronExpressionLTE applies the LTE predicate on the "cron_expression" field.
func CronExpressionLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCronExpression, v))
}

// CronExpressionContains applies the Contains predicate on the "cron_expression" field.
func CronExpressionContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldCronExpression, v))
}

// CronExpressionHasPrefix applies the HasPrefix predicate on the "cron_expression" field.
func CronExpressionHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldCronExpression, v))
}

// CronExpressionHasSuffix applies the HasSuffix predicate on the "cron_expression" field.
func CronExpressionHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldCronExpression, v))
}

// CronExpressionEqualFold applies the EqualFold predicate on the "cron_expression" field.
func CronExpressionEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldCronExpression, v))
}

// CronExpressionContainsFold applies the ContainsFold predicate on the "cron_expression" field.
func CronExpressionContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldCronExpression, v))
}

// MisfirePolicyEQ applies the EQ predicate on the "misfire_policy" field.
func MisfirePolicyEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldMisfirePolicy, v))
}

// MisfirePolicyNEQ applies the NEQ predicate on the "misfire_policy" field.
func MisfirePolicyNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldMisfirePolicy, v))
}

// MisfirePolicyIn applies the In predicate on the "misfire_policy" field.
func MisfirePolicyIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldMisfirePolicy, vs...))
}

// MisfirePolicyNotIn applies the NotIn predicate on the "misfire_policy" field.
func MisfirePolicyNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldMisfirePolicy, vs...))
}

// MisfirePolicyGT applies the GT predicate on the "misfire_policy" field.
func MisfirePolicyGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldMisfirePolicy, v))
}

// MisfirePolicyGTE applies the GTE predicate on the "misfire_policy" field.
func MisfirePolicyGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldMisfirePolicy, v))
}

// MisfirePolicyLT applies the LT predicate on the "misfire_policy" field.
func MisfirePolicyLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldMisfirePolicy, v))
}

// MisfirePolicyLTE applies the LTE predicate on the "misfire_policy" field.
func MisfirePolicyLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldMisfirePolicy, v))
}

// MisfirePolicyContains applies the Contains predicate on the "misfire_policy" field.
func MisfirePolicyContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldMisfirePolicy, v))
}

// MisfirePolicyHasPrefix applies the HasPrefix predicate on the "misfire_policy" field.
func MisfirePolicyHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldMisfirePolicy, v))
}

// MisfirePolicyHasSuffix applies the HasSuffix predicate on the "misfire_policy" field.
func MisfirePolicyHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldMisfirePolicy, v))
}

// MisfirePolicyEqualFold applies the EqualFold predicate on the "misfire_policy" field.
func MisfirePolicyEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldMisfirePolicy, v))
}

// MisfirePolicyContainsFold applies the ContainsFold predicate on the "misfire_policy" field.
func MisfirePolicyContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldMisfirePolicy, v))
}

// ConcurrentEQ applies the EQ predicate on the "concurrent" field.
func ConcurrentEQ(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldConcurrent, v))
}

// ConcurrentNEQ applies the NEQ predicate on the "concurrent" field.
func ConcurrentNEQ(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldConcurrent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldStatus, vs...))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldRemark, v))
}

// NextRunTimeEQ applies the EQ predicate on the "next_run_time" field.
func NextRunTimeEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldNextRunTime, v))
}

// NextRunTimeNEQ applies the NEQ predicate on the "next_run_time" field.
func NextRunTimeNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldNextRunTime, v))
}

// NextRunTimeIn applies the In predicate on the "next_run_time" field.
func NextRunTimeIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldNextRunTime, vs...))
}

// NextRunTimeNotIn applies the NotIn predicate on the "next_run_time" field.
func NextRunTimeNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldNextRunTime, vs...))
}

// NextRunTimeGT applies the GT predicate on the "next_run_time" field.
func NextRunTimeGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldNextRunTime, v))
}

// NextRunTimeGTE applies the GTE predicate on the "next_run_time" field.
func NextRunTimeGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldNextRunTime, v))
}

// NextRunTimeLT applies the LT predicate on the "next_run_time" field.
func NextRunTimeLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldNextRunTime, v))
}

// NextRunTimeLTE applies the LTE predicate on the "next_run_time" field.
func NextRunTimeLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldNextRunTime, v))
}

// NextRunTimeIsNil applies the IsNil predicate on the "next_run_time" field.
func NextRunTimeIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldNextRunTime))
}

// NextRunTimeNotNil applies the NotNil predicate on the "next_run_time" field.
func NextRunTimeNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldNextRunTime))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.NotPredicates(p))
}
