syntax = "proto3";

package permission.service.v1;

import "google/protobuf/empty.proto";
//import "permission/service/v1/role.proto";
import "permission/service/v1/menu.proto";
//import "permission/service/v1/rbac.proto";

service PermissionService {
  // ----- 角色 -----
  //    rpc CreateRole(CreateRoleRequest) returns (CreateRoleResponse);
  //    rpc UpdateRole(UpdateRoleRequest) returns (UpdateRoleResponse);
  //    rpc GetRole(GetRoleRequest) returns (Role);
  //    rpc ListRole(ListRoleRequest) returns (ListRoleResponse);
  //    rpc DeleteRole(DeleteRoleRequest) returns (google.protobuf.Empty);

  // ----- 权限 -----
  rpc CreateMenu(CreateMenuRequest) returns (CreateMenuResponse);
  rpc UpdateMenu(UpdateMenuRequest) returns (UpdateMenuResponse);
  rpc GetMenu(GetMenuRequest) returns (Menu);
  rpc ListMenu(ListMenuRequest) returns (ListMenuResponse);
  rpc MenuTree(MenuTreeRequest) returns (MenuTreeResponse);
  rpc DeleteMenu(DeleteMenuRequest) returns (google.protobuf.Empty);

  // ----- RBAC 绑定与查询 -----
  //    rpc BindRolesForAdmin(BindRolesForAdminRequest) returns (google.protobuf.Empty);
  //    rpc BindMenusForRole(BindMenusForRoleRequest) returns (google.protobuf.Empty);
  //    rpc ListRolesByAdmin(ListRolesByAdminRequest) returns (ListRolesByAdminResponse);
  //    rpc ListMenusByRole(ListMenusByRoleRequest) returns (ListMenusByRoleResponse);
  //    rpc ListMenusByAdmin(ListMenusByAdminRequest) returns (ListMenusByAdminResponse);
  //    rpc CheckMenu(CheckMenuRequest) returns (CheckMenuResponse);
}
