// Code generated by ent, DO NOT EDIT.

package securitypolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldContainsFold(FieldID, id))
}

// LoginFailEnabled applies equality check predicate on the "login_fail_enabled" field. It's identical to LoginFailEnabledEQ.
func LoginFailEnabled(v bool) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailEnabled, v))
}

// LoginFailMax applies equality check predicate on the "login_fail_max" field. It's identical to LoginFailMaxEQ.
func LoginFailMax(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailMax, v))
}

// LoginFailWindowMinutes applies equality check predicate on the "login_fail_window_minutes" field. It's identical to LoginFailWindowMinutesEQ.
func LoginFailWindowMinutes(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailWindowMinutes, v))
}

// LoginLockMinutes applies equality check predicate on the "login_lock_minutes" field. It's identical to LoginLockMinutesEQ.
func LoginLockMinutes(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginLockMinutes, v))
}

// IPList applies equality check predicate on the "ip_list" field. It's identical to IPListEQ.
func IPList(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldIPList, v))
}

// AccessTokenTTLSeconds applies equality check predicate on the "access_token_ttl_seconds" field. It's identical to AccessTokenTTLSecondsEQ.
func AccessTokenTTLSeconds(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSeconds applies equality check predicate on the "refresh_token_ttl_seconds" field. It's identical to RefreshTokenTTLSecondsEQ.
func RefreshTokenTTLSeconds(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldRemark, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// LoginFailEnabledEQ applies the EQ predicate on the "login_fail_enabled" field.
func LoginFailEnabledEQ(v bool) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailEnabled, v))
}

// LoginFailEnabledNEQ applies the NEQ predicate on the "login_fail_enabled" field.
func LoginFailEnabledNEQ(v bool) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldLoginFailEnabled, v))
}

// LoginFailMaxEQ applies the EQ predicate on the "login_fail_max" field.
func LoginFailMaxEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailMax, v))
}

// LoginFailMaxNEQ applies the NEQ predicate on the "login_fail_max" field.
func LoginFailMaxNEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldLoginFailMax, v))
}

// LoginFailMaxIn applies the In predicate on the "login_fail_max" field.
func LoginFailMaxIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldLoginFailMax, vs...))
}

// LoginFailMaxNotIn applies the NotIn predicate on the "login_fail_max" field.
func LoginFailMaxNotIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldLoginFailMax, vs...))
}

// LoginFailMaxGT applies the GT predicate on the "login_fail_max" field.
func LoginFailMaxGT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldLoginFailMax, v))
}

// LoginFailMaxGTE applies the GTE predicate on the "login_fail_max" field.
func LoginFailMaxGTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldLoginFailMax, v))
}

// LoginFailMaxLT applies the LT predicate on the "login_fail_max" field.
func LoginFailMaxLT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldLoginFailMax, v))
}

// LoginFailMaxLTE applies the LTE predicate on the "login_fail_max" field.
func LoginFailMaxLTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldLoginFailMax, v))
}

// LoginFailWindowMinutesEQ applies the EQ predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginFailWindowMinutes, v))
}

// LoginFailWindowMinutesNEQ applies the NEQ predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesNEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldLoginFailWindowMinutes, v))
}

// LoginFailWindowMinutesIn applies the In predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldLoginFailWindowMinutes, vs...))
}

// LoginFailWindowMinutesNotIn applies the NotIn predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesNotIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldLoginFailWindowMinutes, vs...))
}

// LoginFailWindowMinutesGT applies the GT predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesGT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldLoginFailWindowMinutes, v))
}

// LoginFailWindowMinutesGTE applies the GTE predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesGTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldLoginFailWindowMinutes, v))
}

// LoginFailWindowMinutesLT applies the LT predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesLT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldLoginFailWindowMinutes, v))
}

// LoginFailWindowMinutesLTE applies the LTE predicate on the "login_fail_window_minutes" field.
func LoginFailWindowMinutesLTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldLoginFailWindowMinutes, v))
}

// LoginLockMinutesEQ applies the EQ predicate on the "login_lock_minutes" field.
func LoginLockMinutesEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldLoginLockMinutes, v))
}

// LoginLockMinutesNEQ applies the NEQ predicate on the "login_lock_minutes" field.
func LoginLockMinutesNEQ(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldLoginLockMinutes, v))
}

// LoginLockMinutesIn applies the In predicate on the "login_lock_minutes" field.
func LoginLockMinutesIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldLoginLockMinutes, vs...))
}

// LoginLockMinutesNotIn applies the NotIn predicate on the "login_lock_minutes" field.
func LoginLockMinutesNotIn(vs ...int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldLoginLockMinutes, vs...))
}

// LoginLockMinutesGT applies the GT predicate on the "login_lock_minutes" field.
func LoginLockMinutesGT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldLoginLockMinutes, v))
}

// LoginLockMinutesGTE applies the GTE predicate on the "login_lock_minutes" field.
func LoginLockMinutesGTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldLoginLockMinutes, v))
}

// LoginLockMinutesLT applies the LT predicate on the "login_lock_minutes" field.
func LoginLockMinutesLT(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldLoginLockMinutes, v))
}

// LoginLockMinutesLTE applies the LTE predicate on the "login_lock_minutes" field.
func LoginLockMinutesLTE(v int) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldLoginLockMinutes, v))
}

// IPModeEQ applies the EQ predicate on the "ip_mode" field.
func IPModeEQ(v IPMode) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldIPMode, v))
}

// IPModeNEQ applies the NEQ predicate on the "ip_mode" field.
func IPModeNEQ(v IPMode) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldIPMode, v))
}

// IPModeIn applies the In predicate on the "ip_mode" field.
func IPModeIn(vs ...IPMode) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldIPMode, vs...))
}

// IPModeNotIn applies the NotIn predicate on the "ip_mode" field.
func IPModeNotIn(vs ...IPMode) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldIPMode, vs...))
}

// IPListEQ applies the EQ predicate on the "ip_list" field.
func IPListEQ(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldIPList, v))
}

// IPListNEQ applies the NEQ predicate on the "ip_list" field.
func IPListNEQ(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldIPList, v))
}

// IPListIn applies the In predicate on the "ip_list" field.
func IPListIn(vs ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldIPList, vs...))
}

// IPListNotIn applies the NotIn predicate on the "ip_list" field.
func IPListNotIn(vs ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldIPList, vs...))
}

// IPListGT applies the GT predicate on the "ip_list" field.
func IPListGT(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldIPList, v))
}

// IPListGTE applies the GTE predicate on the "ip_list" field.
func IPListGTE(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldIPList, v))
}

// IPListLT applies the LT predicate on the "ip_list" field.
func IPListLT(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldIPList, v))
}

// IPListLTE applies the LTE predicate on the "ip_list" field.
func IPListLTE(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldIPList, v))
}

// IPListContains applies the Contains predicate on the "ip_list" field.
func IPListContains(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldContains(FieldIPList, v))
}

// IPListHasPrefix applies the HasPrefix predicate on the "ip_list" field.
func IPListHasPrefix(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldHasPrefix(FieldIPList, v))
}

// IPListHasSuffix applies the HasSuffix predicate on the "ip_list" field.
func IPListHasSuffix(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldHasSuffix(FieldIPList, v))
}

// IPListIsNil applies the IsNil predicate on the "ip_list" field.
func IPListIsNil() predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIsNull(FieldIPList))
}

// IPListNotNil applies the NotNil predicate on the "ip_list" field.
func IPListNotNil() predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotNull(FieldIPList))
}

// IPListEqualFold applies the EqualFold predicate on the "ip_list" field.
func IPListEqualFold(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEqualFold(FieldIPList, v))
}

// IPListContainsFold applies the ContainsFold predicate on the "ip_list" field.
func IPListContainsFold(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldContainsFold(FieldIPList, v))
}

// AccessTokenTTLSecondsEQ applies the EQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsEQ(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsNEQ applies the NEQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNEQ(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsIn applies the In predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsIn(vs ...int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsNotIn applies the NotIn predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNotIn(vs ...int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsGT applies the GT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGT(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsGTE applies the GTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGTE(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLT applies the LT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLT(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLTE applies the LTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLTE(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsEQ applies the EQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsEQ(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsNEQ applies the NEQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNEQ(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsIn applies the In predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsIn(vs ...int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsNotIn applies the NotIn predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNotIn(vs ...int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsGT applies the GT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGT(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsGTE applies the GTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGTE(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLT applies the LT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLT(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLTE applies the LTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLTE(v int64) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldRefreshTokenTTLSeconds, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldContainsFold(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecurityPolicy) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecurityPolicy) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecurityPolicy) predicate.SecurityPolicy {
	return predicate.SecurityPolicy(sql.NotPredicates(p))
}
