app:
  is_demo: false
server:
  http:
    addr: 0.0.0.0:8888
    timeout: 3s
  grpc:
    addr: 0.0.0.0:9999
    timeout: 3s
data:
  database:
    driver: mysql
    source: root:@tcp(127.0.0.1:3306)/kratos_admin?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: ""
    read_timeout: 3s
    write_timeout: 3s
jwt:
  access_secret: "kratos-admin-access-secret"
  refresh_secret: "kratos-admin-access-refresh"
  issuer: "kratos-admin"
  access_ttl: 7200s
  refresh_ttl: 604800s # 7
mq:
  rabbitmq:
    url: "amqp://guest:guest@127.0.0.1:5672/"
    exchange: "" # 默认交换机
    queue: ""
    routing_key: ""
    prefetch: 10 # 消费限流
    pool_size: 2
    durable: true