// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admin"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admindatapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/datapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// AdminDataPermissionUpdate is the builder for updating AdminDataPermission entities.
type AdminDataPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminDataPermissionMutation
}

// Where appends a list predicates to the AdminDataPermissionUpdate builder.
func (_u *AdminDataPermissionUpdate) Where(ps ...predicate.AdminDataPermission) *AdminDataPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminDataPermissionUpdate) SetAdminID(v string) *AdminDataPermissionUpdate {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminDataPermissionUpdate) SetNillableAdminID(v *string) *AdminDataPermissionUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// SetDataPermissionID sets the "data_permission_id" field.
func (_u *AdminDataPermissionUpdate) SetDataPermissionID(v string) *AdminDataPermissionUpdate {
	_u.mutation.SetDataPermissionID(v)
	return _u
}

// SetNillableDataPermissionID sets the "data_permission_id" field if the given value is not nil.
func (_u *AdminDataPermissionUpdate) SetNillableDataPermissionID(v *string) *AdminDataPermissionUpdate {
	if v != nil {
		_u.SetDataPermissionID(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the Admin entity.
func (_u *AdminDataPermissionUpdate) SetAdmin(v *Admin) *AdminDataPermissionUpdate {
	return _u.SetAdminID(v.ID)
}

// SetDataPermission sets the "data_permission" edge to the DataPermission entity.
func (_u *AdminDataPermissionUpdate) SetDataPermission(v *DataPermission) *AdminDataPermissionUpdate {
	return _u.SetDataPermissionID(v.ID)
}

// Mutation returns the AdminDataPermissionMutation object of the builder.
func (_u *AdminDataPermissionUpdate) Mutation() *AdminDataPermissionMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the Admin entity.
func (_u *AdminDataPermissionUpdate) ClearAdmin() *AdminDataPermissionUpdate {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearDataPermission clears the "data_permission" edge to the DataPermission entity.
func (_u *AdminDataPermissionUpdate) ClearDataPermission() *AdminDataPermissionUpdate {
	_u.mutation.ClearDataPermission()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminDataPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminDataPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminDataPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminDataPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminDataPermissionUpdate) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := admindatapermission.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "AdminDataPermission.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DataPermissionID(); ok {
		if err := admindatapermission.DataPermissionIDValidator(v); err != nil {
			return &ValidationError{Name: "data_permission_id", err: fmt.Errorf(`ent: validator failed for field "AdminDataPermission.data_permission_id": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminDataPermission.admin"`)
	}
	if _u.mutation.DataPermissionCleared() && len(_u.mutation.DataPermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminDataPermission.data_permission"`)
	}
	return nil
}

func (_u *AdminDataPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admindatapermission.Table, admindatapermission.Columns, sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.AdminTable,
			Columns: []string{admindatapermission.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.AdminTable,
			Columns: []string{admindatapermission.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DataPermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.DataPermissionTable,
			Columns: []string{admindatapermission.DataPermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DataPermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.DataPermissionTable,
			Columns: []string{admindatapermission.DataPermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admindatapermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminDataPermissionUpdateOne is the builder for updating a single AdminDataPermission entity.
type AdminDataPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminDataPermissionMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *AdminDataPermissionUpdateOne) SetAdminID(v string) *AdminDataPermissionUpdateOne {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *AdminDataPermissionUpdateOne) SetNillableAdminID(v *string) *AdminDataPermissionUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// SetDataPermissionID sets the "data_permission_id" field.
func (_u *AdminDataPermissionUpdateOne) SetDataPermissionID(v string) *AdminDataPermissionUpdateOne {
	_u.mutation.SetDataPermissionID(v)
	return _u
}

// SetNillableDataPermissionID sets the "data_permission_id" field if the given value is not nil.
func (_u *AdminDataPermissionUpdateOne) SetNillableDataPermissionID(v *string) *AdminDataPermissionUpdateOne {
	if v != nil {
		_u.SetDataPermissionID(*v)
	}
	return _u
}

// SetAdmin sets the "admin" edge to the Admin entity.
func (_u *AdminDataPermissionUpdateOne) SetAdmin(v *Admin) *AdminDataPermissionUpdateOne {
	return _u.SetAdminID(v.ID)
}

// SetDataPermission sets the "data_permission" edge to the DataPermission entity.
func (_u *AdminDataPermissionUpdateOne) SetDataPermission(v *DataPermission) *AdminDataPermissionUpdateOne {
	return _u.SetDataPermissionID(v.ID)
}

// Mutation returns the AdminDataPermissionMutation object of the builder.
func (_u *AdminDataPermissionUpdateOne) Mutation() *AdminDataPermissionMutation {
	return _u.mutation
}

// ClearAdmin clears the "admin" edge to the Admin entity.
func (_u *AdminDataPermissionUpdateOne) ClearAdmin() *AdminDataPermissionUpdateOne {
	_u.mutation.ClearAdmin()
	return _u
}

// ClearDataPermission clears the "data_permission" edge to the DataPermission entity.
func (_u *AdminDataPermissionUpdateOne) ClearDataPermission() *AdminDataPermissionUpdateOne {
	_u.mutation.ClearDataPermission()
	return _u
}

// Where appends a list predicates to the AdminDataPermissionUpdate builder.
func (_u *AdminDataPermissionUpdateOne) Where(ps ...predicate.AdminDataPermission) *AdminDataPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminDataPermissionUpdateOne) Select(field string, fields ...string) *AdminDataPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminDataPermission entity.
func (_u *AdminDataPermissionUpdateOne) Save(ctx context.Context) (*AdminDataPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminDataPermissionUpdateOne) SaveX(ctx context.Context) *AdminDataPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminDataPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminDataPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminDataPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := admindatapermission.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "AdminDataPermission.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DataPermissionID(); ok {
		if err := admindatapermission.DataPermissionIDValidator(v); err != nil {
			return &ValidationError{Name: "data_permission_id", err: fmt.Errorf(`ent: validator failed for field "AdminDataPermission.data_permission_id": %w`, err)}
		}
	}
	if _u.mutation.AdminCleared() && len(_u.mutation.AdminIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminDataPermission.admin"`)
	}
	if _u.mutation.DataPermissionCleared() && len(_u.mutation.DataPermissionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminDataPermission.data_permission"`)
	}
	return nil
}

func (_u *AdminDataPermissionUpdateOne) sqlSave(ctx context.Context) (_node *AdminDataPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(admindatapermission.Table, admindatapermission.Columns, sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminDataPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, admindatapermission.FieldID)
		for _, f := range fields {
			if !admindatapermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != admindatapermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.AdminTable,
			Columns: []string{admindatapermission.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.AdminTable,
			Columns: []string{admindatapermission.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DataPermissionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.DataPermissionTable,
			Columns: []string{admindatapermission.DataPermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DataPermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   admindatapermission.DataPermissionTable,
			Columns: []string{admindatapermission.DataPermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminDataPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{admindatapermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
