// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/apipermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/menu"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// ApiPermissionUpdate is the builder for updating ApiPermission entities.
type ApiPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *ApiPermissionMutation
}

// Where appends a list predicates to the ApiPermissionUpdate builder.
func (_u *ApiPermissionUpdate) Where(ps ...predicate.ApiPermission) *ApiPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetService sets the "service" field.
func (_u *ApiPermissionUpdate) SetService(v string) *ApiPermissionUpdate {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ApiPermissionUpdate) SetNillableService(v *string) *ApiPermissionUpdate {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *ApiPermissionUpdate) SetMethod(v string) *ApiPermissionUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *ApiPermissionUpdate) SetNillableMethod(v *string) *ApiPermissionUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ApiPermissionUpdate) SetPath(v string) *ApiPermissionUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ApiPermissionUpdate) SetNillablePath(v *string) *ApiPermissionUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ApiPermissionUpdate) SetSummary(v string) *ApiPermissionUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ApiPermissionUpdate) SetNillableSummary(v *string) *ApiPermissionUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ApiPermissionUpdate) SetCode(v string) *ApiPermissionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ApiPermissionUpdate) SetNillableCode(v *string) *ApiPermissionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *ApiPermissionUpdate) AddMenuIDs(ids ...string) *ApiPermissionUpdate {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *ApiPermissionUpdate) AddMenus(v ...*Menu) *ApiPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// Mutation returns the ApiPermissionMutation object of the builder.
func (_u *ApiPermissionUpdate) Mutation() *ApiPermissionMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *ApiPermissionUpdate) ClearMenus() *ApiPermissionUpdate {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *ApiPermissionUpdate) RemoveMenuIDs(ids ...string) *ApiPermissionUpdate {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *ApiPermissionUpdate) RemoveMenus(v ...*Menu) *ApiPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiPermissionUpdate) check() error {
	if v, ok := _u.mutation.Service(); ok {
		if err := apipermission.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.service": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := apipermission.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := apipermission.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := apipermission.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := apipermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ApiPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apipermission.Table, apipermission.Columns, sqlgraph.NewFieldSpec(apipermission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(apipermission.FieldService, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apipermission.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apipermission.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(apipermission.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(apipermission.FieldCode, field.TypeString, value)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apipermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiPermissionUpdateOne is the builder for updating a single ApiPermission entity.
type ApiPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiPermissionMutation
}

// SetService sets the "service" field.
func (_u *ApiPermissionUpdateOne) SetService(v string) *ApiPermissionUpdateOne {
	_u.mutation.SetService(v)
	return _u
}

// SetNillableService sets the "service" field if the given value is not nil.
func (_u *ApiPermissionUpdateOne) SetNillableService(v *string) *ApiPermissionUpdateOne {
	if v != nil {
		_u.SetService(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *ApiPermissionUpdateOne) SetMethod(v string) *ApiPermissionUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *ApiPermissionUpdateOne) SetNillableMethod(v *string) *ApiPermissionUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ApiPermissionUpdateOne) SetPath(v string) *ApiPermissionUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ApiPermissionUpdateOne) SetNillablePath(v *string) *ApiPermissionUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ApiPermissionUpdateOne) SetSummary(v string) *ApiPermissionUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ApiPermissionUpdateOne) SetNillableSummary(v *string) *ApiPermissionUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ApiPermissionUpdateOne) SetCode(v string) *ApiPermissionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ApiPermissionUpdateOne) SetNillableCode(v *string) *ApiPermissionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *ApiPermissionUpdateOne) AddMenuIDs(ids ...string) *ApiPermissionUpdateOne {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *ApiPermissionUpdateOne) AddMenus(v ...*Menu) *ApiPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// Mutation returns the ApiPermissionMutation object of the builder.
func (_u *ApiPermissionUpdateOne) Mutation() *ApiPermissionMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *ApiPermissionUpdateOne) ClearMenus() *ApiPermissionUpdateOne {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *ApiPermissionUpdateOne) RemoveMenuIDs(ids ...string) *ApiPermissionUpdateOne {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *ApiPermissionUpdateOne) RemoveMenus(v ...*Menu) *ApiPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// Where appends a list predicates to the ApiPermissionUpdate builder.
func (_u *ApiPermissionUpdateOne) Where(ps ...predicate.ApiPermission) *ApiPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiPermissionUpdateOne) Select(field string, fields ...string) *ApiPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiPermission entity.
func (_u *ApiPermissionUpdateOne) Save(ctx context.Context) (*ApiPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiPermissionUpdateOne) SaveX(ctx context.Context) *ApiPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Service(); ok {
		if err := apipermission.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.service": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := apipermission.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := apipermission.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := apipermission.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := apipermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ApiPermission.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ApiPermissionUpdateOne) sqlSave(ctx context.Context) (_node *ApiPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apipermission.Table, apipermission.Columns, sqlgraph.NewFieldSpec(apipermission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apipermission.FieldID)
		for _, f := range fields {
			if !apipermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apipermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Service(); ok {
		_spec.SetField(apipermission.FieldService, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(apipermission.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(apipermission.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(apipermission.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(apipermission.FieldCode, field.TypeString, value)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   apipermission.MenusTable,
			Columns: apipermission.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apipermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
