// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admin"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admindatapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/datapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/role"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/roledatapermission"
)

// DataPermissionQuery is the builder for querying DataPermission entities.
type DataPermissionQuery struct {
	config
	ctx                      *QueryContext
	order                    []datapermission.OrderOption
	inters                   []Interceptor
	predicates               []predicate.DataPermission
	withRoles                *RoleQuery
	withAdmins               *AdminQuery
	withRoleDataPermissions  *RoleDataPermissionQuery
	withAdminDataPermissions *AdminDataPermissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DataPermissionQuery builder.
func (_q *DataPermissionQuery) Where(ps ...predicate.DataPermission) *DataPermissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DataPermissionQuery) Limit(limit int) *DataPermissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DataPermissionQuery) Offset(offset int) *DataPermissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DataPermissionQuery) Unique(unique bool) *DataPermissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DataPermissionQuery) Order(o ...datapermission.OrderOption) *DataPermissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRoles chains the current query on the "roles" edge.
func (_q *DataPermissionQuery) QueryRoles() *RoleQuery {
	query := (&RoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(datapermission.Table, datapermission.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, datapermission.RolesTable, datapermission.RolesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdmins chains the current query on the "admins" edge.
func (_q *DataPermissionQuery) QueryAdmins() *AdminQuery {
	query := (&AdminClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(datapermission.Table, datapermission.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, datapermission.AdminsTable, datapermission.AdminsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoleDataPermissions chains the current query on the "role_data_permissions" edge.
func (_q *DataPermissionQuery) QueryRoleDataPermissions() *RoleDataPermissionQuery {
	query := (&RoleDataPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(datapermission.Table, datapermission.FieldID, selector),
			sqlgraph.To(roledatapermission.Table, roledatapermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, datapermission.RoleDataPermissionsTable, datapermission.RoleDataPermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdminDataPermissions chains the current query on the "admin_data_permissions" edge.
func (_q *DataPermissionQuery) QueryAdminDataPermissions() *AdminDataPermissionQuery {
	query := (&AdminDataPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(datapermission.Table, datapermission.FieldID, selector),
			sqlgraph.To(admindatapermission.Table, admindatapermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, datapermission.AdminDataPermissionsTable, datapermission.AdminDataPermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DataPermission entity from the query.
// Returns a *NotFoundError when no DataPermission was found.
func (_q *DataPermissionQuery) First(ctx context.Context) (*DataPermission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{datapermission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DataPermissionQuery) FirstX(ctx context.Context) *DataPermission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DataPermission ID from the query.
// Returns a *NotFoundError when no DataPermission ID was found.
func (_q *DataPermissionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{datapermission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DataPermissionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DataPermission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DataPermission entity is found.
// Returns a *NotFoundError when no DataPermission entities are found.
func (_q *DataPermissionQuery) Only(ctx context.Context) (*DataPermission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{datapermission.Label}
	default:
		return nil, &NotSingularError{datapermission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DataPermissionQuery) OnlyX(ctx context.Context) *DataPermission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DataPermission ID in the query.
// Returns a *NotSingularError when more than one DataPermission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DataPermissionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{datapermission.Label}
	default:
		err = &NotSingularError{datapermission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DataPermissionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DataPermissions.
func (_q *DataPermissionQuery) All(ctx context.Context) ([]*DataPermission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DataPermission, *DataPermissionQuery]()
	return withInterceptors[[]*DataPermission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DataPermissionQuery) AllX(ctx context.Context) []*DataPermission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DataPermission IDs.
func (_q *DataPermissionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(datapermission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DataPermissionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DataPermissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DataPermissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DataPermissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DataPermissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DataPermissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DataPermissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DataPermissionQuery) Clone() *DataPermissionQuery {
	if _q == nil {
		return nil
	}
	return &DataPermissionQuery{
		config:                   _q.config,
		ctx:                      _q.ctx.Clone(),
		order:                    append([]datapermission.OrderOption{}, _q.order...),
		inters:                   append([]Interceptor{}, _q.inters...),
		predicates:               append([]predicate.DataPermission{}, _q.predicates...),
		withRoles:                _q.withRoles.Clone(),
		withAdmins:               _q.withAdmins.Clone(),
		withRoleDataPermissions:  _q.withRoleDataPermissions.Clone(),
		withAdminDataPermissions: _q.withAdminDataPermissions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DataPermissionQuery) WithRoles(opts ...func(*RoleQuery)) *DataPermissionQuery {
	query := (&RoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoles = query
	return _q
}

// WithAdmins tells the query-builder to eager-load the nodes that are connected to
// the "admins" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DataPermissionQuery) WithAdmins(opts ...func(*AdminQuery)) *DataPermissionQuery {
	query := (&AdminClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdmins = query
	return _q
}

// WithRoleDataPermissions tells the query-builder to eager-load the nodes that are connected to
// the "role_data_permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DataPermissionQuery) WithRoleDataPermissions(opts ...func(*RoleDataPermissionQuery)) *DataPermissionQuery {
	query := (&RoleDataPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoleDataPermissions = query
	return _q
}

// WithAdminDataPermissions tells the query-builder to eager-load the nodes that are connected to
// the "admin_data_permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DataPermissionQuery) WithAdminDataPermissions(opts ...func(*AdminDataPermissionQuery)) *DataPermissionQuery {
	query := (&AdminDataPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAdminDataPermissions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DataPermission.Query().
//		GroupBy(datapermission.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DataPermissionQuery) GroupBy(field string, fields ...string) *DataPermissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DataPermissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = datapermission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.DataPermission.Query().
//		Select(datapermission.FieldTenantID).
//		Scan(ctx, &v)
func (_q *DataPermissionQuery) Select(fields ...string) *DataPermissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DataPermissionSelect{DataPermissionQuery: _q}
	sbuild.label = datapermission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DataPermissionSelect configured with the given aggregations.
func (_q *DataPermissionQuery) Aggregate(fns ...AggregateFunc) *DataPermissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DataPermissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !datapermission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DataPermissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DataPermission, error) {
	var (
		nodes       = []*DataPermission{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withRoles != nil,
			_q.withAdmins != nil,
			_q.withRoleDataPermissions != nil,
			_q.withAdminDataPermissions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DataPermission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DataPermission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRoles; query != nil {
		if err := _q.loadRoles(ctx, query, nodes,
			func(n *DataPermission) { n.Edges.Roles = []*Role{} },
			func(n *DataPermission, e *Role) { n.Edges.Roles = append(n.Edges.Roles, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdmins; query != nil {
		if err := _q.loadAdmins(ctx, query, nodes,
			func(n *DataPermission) { n.Edges.Admins = []*Admin{} },
			func(n *DataPermission, e *Admin) { n.Edges.Admins = append(n.Edges.Admins, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoleDataPermissions; query != nil {
		if err := _q.loadRoleDataPermissions(ctx, query, nodes,
			func(n *DataPermission) { n.Edges.RoleDataPermissions = []*RoleDataPermission{} },
			func(n *DataPermission, e *RoleDataPermission) {
				n.Edges.RoleDataPermissions = append(n.Edges.RoleDataPermissions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withAdminDataPermissions; query != nil {
		if err := _q.loadAdminDataPermissions(ctx, query, nodes,
			func(n *DataPermission) { n.Edges.AdminDataPermissions = []*AdminDataPermission{} },
			func(n *DataPermission, e *AdminDataPermission) {
				n.Edges.AdminDataPermissions = append(n.Edges.AdminDataPermissions, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DataPermissionQuery) loadRoles(ctx context.Context, query *RoleQuery, nodes []*DataPermission, init func(*DataPermission), assign func(*DataPermission, *Role)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*DataPermission)
	nids := make(map[string]map[*DataPermission]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(datapermission.RolesTable)
		s.Join(joinT).On(s.C(role.FieldID), joinT.C(datapermission.RolesPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(datapermission.RolesPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(datapermission.RolesPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*DataPermission]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Role](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "roles" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *DataPermissionQuery) loadAdmins(ctx context.Context, query *AdminQuery, nodes []*DataPermission, init func(*DataPermission), assign func(*DataPermission, *Admin)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*DataPermission)
	nids := make(map[string]map[*DataPermission]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(datapermission.AdminsTable)
		s.Join(joinT).On(s.C(admin.FieldID), joinT.C(datapermission.AdminsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(datapermission.AdminsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(datapermission.AdminsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullString).String
				if nids[inValue] == nil {
					nids[inValue] = map[*DataPermission]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Admin](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "admins" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *DataPermissionQuery) loadRoleDataPermissions(ctx context.Context, query *RoleDataPermissionQuery, nodes []*DataPermission, init func(*DataPermission), assign func(*DataPermission, *RoleDataPermission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*DataPermission)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(roledatapermission.FieldDataPermissionID)
	}
	query.Where(predicate.RoleDataPermission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(datapermission.RoleDataPermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DataPermissionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "data_permission_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DataPermissionQuery) loadAdminDataPermissions(ctx context.Context, query *AdminDataPermissionQuery, nodes []*DataPermission, init func(*DataPermission), assign func(*DataPermission, *AdminDataPermission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*DataPermission)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(admindatapermission.FieldDataPermissionID)
	}
	query.Where(predicate.AdminDataPermission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(datapermission.AdminDataPermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DataPermissionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "data_permission_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DataPermissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DataPermissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(datapermission.Table, datapermission.Columns, sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datapermission.FieldID)
		for i := range fields {
			if fields[i] != datapermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DataPermissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(datapermission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = datapermission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DataPermissionGroupBy is the group-by builder for DataPermission entities.
type DataPermissionGroupBy struct {
	selector
	build *DataPermissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DataPermissionGroupBy) Aggregate(fns ...AggregateFunc) *DataPermissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DataPermissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DataPermissionQuery, *DataPermissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DataPermissionGroupBy) sqlScan(ctx context.Context, root *DataPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DataPermissionSelect is the builder for selecting fields of DataPermission entities.
type DataPermissionSelect struct {
	*DataPermissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DataPermissionSelect) Aggregate(fns ...AggregateFunc) *DataPermissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DataPermissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DataPermissionQuery, *DataPermissionSelect](ctx, _s.DataPermissionQuery, _s, _s.inters, v)
}

func (_s *DataPermissionSelect) sqlScan(ctx context.Context, root *DataPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
