// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admin"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admindatapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/datapermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/role"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/roledatapermission"
)

// DataPermissionUpdate is the builder for updating DataPermission entities.
type DataPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *DataPermissionMutation
}

// Where appends a list predicates to the DataPermissionUpdate builder.
func (_u *DataPermissionUpdate) Where(ps ...predicate.DataPermission) *DataPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DataPermissionUpdate) SetName(v string) *DataPermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableName(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *DataPermissionUpdate) SetCode(v string) *DataPermissionUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableCode(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *DataPermissionUpdate) SetScopeType(v string) *DataPermissionUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableScopeType(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetDeptIds sets the "dept_ids" field.
func (_u *DataPermissionUpdate) SetDeptIds(v string) *DataPermissionUpdate {
	_u.mutation.SetDeptIds(v)
	return _u
}

// SetNillableDeptIds sets the "dept_ids" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableDeptIds(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetDeptIds(*v)
	}
	return _u
}

// ClearDeptIds clears the value of the "dept_ids" field.
func (_u *DataPermissionUpdate) ClearDeptIds() *DataPermissionUpdate {
	_u.mutation.ClearDeptIds()
	return _u
}

// SetRoleIds sets the "role_ids" field.
func (_u *DataPermissionUpdate) SetRoleIds(v string) *DataPermissionUpdate {
	_u.mutation.SetRoleIds(v)
	return _u
}

// SetNillableRoleIds sets the "role_ids" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableRoleIds(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetRoleIds(*v)
	}
	return _u
}

// ClearRoleIds clears the value of the "role_ids" field.
func (_u *DataPermissionUpdate) ClearRoleIds() *DataPermissionUpdate {
	_u.mutation.ClearRoleIds()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DataPermissionUpdate) SetStatus(v datapermission.Status) *DataPermissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableStatus(v *datapermission.Status) *DataPermissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DataPermissionUpdate) SetRemark(v string) *DataPermissionUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableRemark(v *string) *DataPermissionUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DataPermissionUpdate) ClearRemark() *DataPermissionUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DataPermissionUpdate) SetUpdatedAt(v time.Time) *DataPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DataPermissionUpdate) SetDeletedAt(v time.Time) *DataPermissionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DataPermissionUpdate) SetNillableDeletedAt(v *time.Time) *DataPermissionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DataPermissionUpdate) ClearDeletedAt() *DataPermissionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *DataPermissionUpdate) AddRoleIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *DataPermissionUpdate) AddRoles(v ...*Role) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the Admin entity by IDs.
func (_u *DataPermissionUpdate) AddAdminIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the Admin entity.
func (_u *DataPermissionUpdate) AddAdmins(v ...*Admin) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddRoleDataPermissionIDs adds the "role_data_permissions" edge to the RoleDataPermission entity by IDs.
func (_u *DataPermissionUpdate) AddRoleDataPermissionIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.AddRoleDataPermissionIDs(ids...)
	return _u
}

// AddRoleDataPermissions adds the "role_data_permissions" edges to the RoleDataPermission entity.
func (_u *DataPermissionUpdate) AddRoleDataPermissions(v ...*RoleDataPermission) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleDataPermissionIDs(ids...)
}

// AddAdminDataPermissionIDs adds the "admin_data_permissions" edge to the AdminDataPermission entity by IDs.
func (_u *DataPermissionUpdate) AddAdminDataPermissionIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.AddAdminDataPermissionIDs(ids...)
	return _u
}

// AddAdminDataPermissions adds the "admin_data_permissions" edges to the AdminDataPermission entity.
func (_u *DataPermissionUpdate) AddAdminDataPermissions(v ...*AdminDataPermission) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminDataPermissionIDs(ids...)
}

// Mutation returns the DataPermissionMutation object of the builder.
func (_u *DataPermissionUpdate) Mutation() *DataPermissionMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *DataPermissionUpdate) ClearRoles() *DataPermissionUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *DataPermissionUpdate) RemoveRoleIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *DataPermissionUpdate) RemoveRoles(v ...*Role) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the Admin entity.
func (_u *DataPermissionUpdate) ClearAdmins() *DataPermissionUpdate {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to Admin entities by IDs.
func (_u *DataPermissionUpdate) RemoveAdminIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to Admin entities.
func (_u *DataPermissionUpdate) RemoveAdmins(v ...*Admin) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearRoleDataPermissions clears all "role_data_permissions" edges to the RoleDataPermission entity.
func (_u *DataPermissionUpdate) ClearRoleDataPermissions() *DataPermissionUpdate {
	_u.mutation.ClearRoleDataPermissions()
	return _u
}

// RemoveRoleDataPermissionIDs removes the "role_data_permissions" edge to RoleDataPermission entities by IDs.
func (_u *DataPermissionUpdate) RemoveRoleDataPermissionIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.RemoveRoleDataPermissionIDs(ids...)
	return _u
}

// RemoveRoleDataPermissions removes "role_data_permissions" edges to RoleDataPermission entities.
func (_u *DataPermissionUpdate) RemoveRoleDataPermissions(v ...*RoleDataPermission) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleDataPermissionIDs(ids...)
}

// ClearAdminDataPermissions clears all "admin_data_permissions" edges to the AdminDataPermission entity.
func (_u *DataPermissionUpdate) ClearAdminDataPermissions() *DataPermissionUpdate {
	_u.mutation.ClearAdminDataPermissions()
	return _u
}

// RemoveAdminDataPermissionIDs removes the "admin_data_permissions" edge to AdminDataPermission entities by IDs.
func (_u *DataPermissionUpdate) RemoveAdminDataPermissionIDs(ids ...string) *DataPermissionUpdate {
	_u.mutation.RemoveAdminDataPermissionIDs(ids...)
	return _u
}

// RemoveAdminDataPermissions removes "admin_data_permissions" edges to AdminDataPermission entities.
func (_u *DataPermissionUpdate) RemoveAdminDataPermissions(v ...*AdminDataPermission) *DataPermissionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminDataPermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DataPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DataPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DataPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := datapermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DataPermissionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := datapermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DataPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := datapermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DataPermission.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := datapermission.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "DataPermission.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeptIds(); ok {
		if err := datapermission.DeptIdsValidator(v); err != nil {
			return &ValidationError{Name: "dept_ids", err: fmt.Errorf(`ent: validator failed for field "DataPermission.dept_ids": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleIds(); ok {
		if err := datapermission.RoleIdsValidator(v); err != nil {
			return &ValidationError{Name: "role_ids", err: fmt.Errorf(`ent: validator failed for field "DataPermission.role_ids": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := datapermission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DataPermission.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := datapermission.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "DataPermission.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *DataPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(datapermission.Table, datapermission.Columns, sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(datapermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(datapermission.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(datapermission.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptIds(); ok {
		_spec.SetField(datapermission.FieldDeptIds, field.TypeString, value)
	}
	if _u.mutation.DeptIdsCleared() {
		_spec.ClearField(datapermission.FieldDeptIds, field.TypeString)
	}
	if value, ok := _u.mutation.RoleIds(); ok {
		_spec.SetField(datapermission.FieldRoleIds, field.TypeString, value)
	}
	if _u.mutation.RoleIdsCleared() {
		_spec.ClearField(datapermission.FieldRoleIds, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(datapermission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(datapermission.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(datapermission.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(datapermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(datapermission.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(datapermission.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleDataPermissionsIDs(); len(nodes) > 0 && !_u.mutation.RoleDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleDataPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminDataPermissionsIDs(); len(nodes) > 0 && !_u.mutation.AdminDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminDataPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datapermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DataPermissionUpdateOne is the builder for updating a single DataPermission entity.
type DataPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DataPermissionMutation
}

// SetName sets the "name" field.
func (_u *DataPermissionUpdateOne) SetName(v string) *DataPermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableName(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *DataPermissionUpdateOne) SetCode(v string) *DataPermissionUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableCode(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *DataPermissionUpdateOne) SetScopeType(v string) *DataPermissionUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableScopeType(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetDeptIds sets the "dept_ids" field.
func (_u *DataPermissionUpdateOne) SetDeptIds(v string) *DataPermissionUpdateOne {
	_u.mutation.SetDeptIds(v)
	return _u
}

// SetNillableDeptIds sets the "dept_ids" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableDeptIds(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetDeptIds(*v)
	}
	return _u
}

// ClearDeptIds clears the value of the "dept_ids" field.
func (_u *DataPermissionUpdateOne) ClearDeptIds() *DataPermissionUpdateOne {
	_u.mutation.ClearDeptIds()
	return _u
}

// SetRoleIds sets the "role_ids" field.
func (_u *DataPermissionUpdateOne) SetRoleIds(v string) *DataPermissionUpdateOne {
	_u.mutation.SetRoleIds(v)
	return _u
}

// SetNillableRoleIds sets the "role_ids" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableRoleIds(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetRoleIds(*v)
	}
	return _u
}

// ClearRoleIds clears the value of the "role_ids" field.
func (_u *DataPermissionUpdateOne) ClearRoleIds() *DataPermissionUpdateOne {
	_u.mutation.ClearRoleIds()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DataPermissionUpdateOne) SetStatus(v datapermission.Status) *DataPermissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableStatus(v *datapermission.Status) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DataPermissionUpdateOne) SetRemark(v string) *DataPermissionUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableRemark(v *string) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DataPermissionUpdateOne) ClearRemark() *DataPermissionUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DataPermissionUpdateOne) SetUpdatedAt(v time.Time) *DataPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DataPermissionUpdateOne) SetDeletedAt(v time.Time) *DataPermissionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DataPermissionUpdateOne) SetNillableDeletedAt(v *time.Time) *DataPermissionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DataPermissionUpdateOne) ClearDeletedAt() *DataPermissionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *DataPermissionUpdateOne) AddRoleIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *DataPermissionUpdateOne) AddRoles(v ...*Role) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the Admin entity by IDs.
func (_u *DataPermissionUpdateOne) AddAdminIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the Admin entity.
func (_u *DataPermissionUpdateOne) AddAdmins(v ...*Admin) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddRoleDataPermissionIDs adds the "role_data_permissions" edge to the RoleDataPermission entity by IDs.
func (_u *DataPermissionUpdateOne) AddRoleDataPermissionIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.AddRoleDataPermissionIDs(ids...)
	return _u
}

// AddRoleDataPermissions adds the "role_data_permissions" edges to the RoleDataPermission entity.
func (_u *DataPermissionUpdateOne) AddRoleDataPermissions(v ...*RoleDataPermission) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleDataPermissionIDs(ids...)
}

// AddAdminDataPermissionIDs adds the "admin_data_permissions" edge to the AdminDataPermission entity by IDs.
func (_u *DataPermissionUpdateOne) AddAdminDataPermissionIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.AddAdminDataPermissionIDs(ids...)
	return _u
}

// AddAdminDataPermissions adds the "admin_data_permissions" edges to the AdminDataPermission entity.
func (_u *DataPermissionUpdateOne) AddAdminDataPermissions(v ...*AdminDataPermission) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminDataPermissionIDs(ids...)
}

// Mutation returns the DataPermissionMutation object of the builder.
func (_u *DataPermissionUpdateOne) Mutation() *DataPermissionMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *DataPermissionUpdateOne) ClearRoles() *DataPermissionUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *DataPermissionUpdateOne) RemoveRoleIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *DataPermissionUpdateOne) RemoveRoles(v ...*Role) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the Admin entity.
func (_u *DataPermissionUpdateOne) ClearAdmins() *DataPermissionUpdateOne {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to Admin entities by IDs.
func (_u *DataPermissionUpdateOne) RemoveAdminIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to Admin entities.
func (_u *DataPermissionUpdateOne) RemoveAdmins(v ...*Admin) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearRoleDataPermissions clears all "role_data_permissions" edges to the RoleDataPermission entity.
func (_u *DataPermissionUpdateOne) ClearRoleDataPermissions() *DataPermissionUpdateOne {
	_u.mutation.ClearRoleDataPermissions()
	return _u
}

// RemoveRoleDataPermissionIDs removes the "role_data_permissions" edge to RoleDataPermission entities by IDs.
func (_u *DataPermissionUpdateOne) RemoveRoleDataPermissionIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.RemoveRoleDataPermissionIDs(ids...)
	return _u
}

// RemoveRoleDataPermissions removes "role_data_permissions" edges to RoleDataPermission entities.
func (_u *DataPermissionUpdateOne) RemoveRoleDataPermissions(v ...*RoleDataPermission) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleDataPermissionIDs(ids...)
}

// ClearAdminDataPermissions clears all "admin_data_permissions" edges to the AdminDataPermission entity.
func (_u *DataPermissionUpdateOne) ClearAdminDataPermissions() *DataPermissionUpdateOne {
	_u.mutation.ClearAdminDataPermissions()
	return _u
}

// RemoveAdminDataPermissionIDs removes the "admin_data_permissions" edge to AdminDataPermission entities by IDs.
func (_u *DataPermissionUpdateOne) RemoveAdminDataPermissionIDs(ids ...string) *DataPermissionUpdateOne {
	_u.mutation.RemoveAdminDataPermissionIDs(ids...)
	return _u
}

// RemoveAdminDataPermissions removes "admin_data_permissions" edges to AdminDataPermission entities.
func (_u *DataPermissionUpdateOne) RemoveAdminDataPermissions(v ...*AdminDataPermission) *DataPermissionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminDataPermissionIDs(ids...)
}

// Where appends a list predicates to the DataPermissionUpdate builder.
func (_u *DataPermissionUpdateOne) Where(ps ...predicate.DataPermission) *DataPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DataPermissionUpdateOne) Select(field string, fields ...string) *DataPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DataPermission entity.
func (_u *DataPermissionUpdateOne) Save(ctx context.Context) (*DataPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DataPermissionUpdateOne) SaveX(ctx context.Context) *DataPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DataPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DataPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DataPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := datapermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DataPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := datapermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DataPermission.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := datapermission.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DataPermission.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := datapermission.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "DataPermission.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeptIds(); ok {
		if err := datapermission.DeptIdsValidator(v); err != nil {
			return &ValidationError{Name: "dept_ids", err: fmt.Errorf(`ent: validator failed for field "DataPermission.dept_ids": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleIds(); ok {
		if err := datapermission.RoleIdsValidator(v); err != nil {
			return &ValidationError{Name: "role_ids", err: fmt.Errorf(`ent: validator failed for field "DataPermission.role_ids": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := datapermission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DataPermission.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := datapermission.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "DataPermission.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *DataPermissionUpdateOne) sqlSave(ctx context.Context) (_node *DataPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(datapermission.Table, datapermission.Columns, sqlgraph.NewFieldSpec(datapermission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DataPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, datapermission.FieldID)
		for _, f := range fields {
			if !datapermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != datapermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(datapermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(datapermission.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(datapermission.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptIds(); ok {
		_spec.SetField(datapermission.FieldDeptIds, field.TypeString, value)
	}
	if _u.mutation.DeptIdsCleared() {
		_spec.ClearField(datapermission.FieldDeptIds, field.TypeString)
	}
	if value, ok := _u.mutation.RoleIds(); ok {
		_spec.SetField(datapermission.FieldRoleIds, field.TypeString, value)
	}
	if _u.mutation.RoleIdsCleared() {
		_spec.ClearField(datapermission.FieldRoleIds, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(datapermission.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(datapermission.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(datapermission.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(datapermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(datapermission.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(datapermission.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.RolesTable,
			Columns: datapermission.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleDataPermissionCreate{config: _u.config, mutation: newRoleDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   datapermission.AdminsTable,
			Columns: datapermission.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminDataPermissionCreate{config: _u.config, mutation: newAdminDataPermissionMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleDataPermissionsIDs(); len(nodes) > 0 && !_u.mutation.RoleDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleDataPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.RoleDataPermissionsTable,
			Columns: []string{datapermission.RoleDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roledatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminDataPermissionsIDs(); len(nodes) > 0 && !_u.mutation.AdminDataPermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminDataPermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   datapermission.AdminDataPermissionsTable,
			Columns: []string{datapermission.AdminDataPermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admindatapermission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DataPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{datapermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
