// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/department"
)

// DepartmentCreate is the builder for creating a Department entity.
type DepartmentCreate struct {
	config
	mutation *DepartmentMutation
	hooks    []Hook
}

// SetParentID sets the "parent_id" field.
func (_c *DepartmentCreate) SetParentID(v string) *DepartmentCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableParentID(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DepartmentCreate) SetName(v string) *DepartmentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *DepartmentCreate) SetCode(v string) *DepartmentCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetType sets the "type" field.
func (_c *DepartmentCreate) SetType(v department.Type) *DepartmentCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetWeight sets the "weight" field.
func (_c *DepartmentCreate) SetWeight(v int) *DepartmentCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableWeight(v *int) *DepartmentCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DepartmentCreate) SetStatus(v department.Status) *DepartmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableStatus(v *department.Status) *DepartmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLeaderName sets the "leader_name" field.
func (_c *DepartmentCreate) SetLeaderName(v string) *DepartmentCreate {
	_c.mutation.SetLeaderName(v)
	return _c
}

// SetNillableLeaderName sets the "leader_name" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableLeaderName(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetLeaderName(*v)
	}
	return _c
}

// SetLeaderPhone sets the "leader_phone" field.
func (_c *DepartmentCreate) SetLeaderPhone(v string) *DepartmentCreate {
	_c.mutation.SetLeaderPhone(v)
	return _c
}

// SetNillableLeaderPhone sets the "leader_phone" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableLeaderPhone(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetLeaderPhone(*v)
	}
	return _c
}

// SetLeaderEmail sets the "leader_email" field.
func (_c *DepartmentCreate) SetLeaderEmail(v string) *DepartmentCreate {
	_c.mutation.SetLeaderEmail(v)
	return _c
}

// SetNillableLeaderEmail sets the "leader_email" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableLeaderEmail(v *string) *DepartmentCreate {
	if v != nil {
		_c.SetLeaderEmail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DepartmentCreate) SetCreatedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableCreatedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DepartmentCreate) SetUpdatedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableUpdatedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DepartmentCreate) SetDeletedAt(v time.Time) *DepartmentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DepartmentCreate) SetNillableDeletedAt(v *time.Time) *DepartmentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DepartmentCreate) SetID(v string) *DepartmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DepartmentMutation object of the builder.
func (_c *DepartmentCreate) Mutation() *DepartmentMutation {
	return _c.mutation
}

// Save creates the Department in the database.
func (_c *DepartmentCreate) Save(ctx context.Context) (*Department, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DepartmentCreate) SaveX(ctx context.Context) *Department {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DepartmentCreate) defaults() {
	if _, ok := _c.mutation.ParentID(); !ok {
		v := department.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := department.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := department.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := department.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := department.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DepartmentCreate) check() error {
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Department.parent_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Department.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := department.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Department.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Department.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := department.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Department.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Department.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := department.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Department.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Department.weight"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Department.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := department.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Department.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaderName(); ok {
		if err := department.LeaderNameValidator(v); err != nil {
			return &ValidationError{Name: "leader_name", err: fmt.Errorf(`ent: validator failed for field "Department.leader_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaderPhone(); ok {
		if err := department.LeaderPhoneValidator(v); err != nil {
			return &ValidationError{Name: "leader_phone", err: fmt.Errorf(`ent: validator failed for field "Department.leader_phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LeaderEmail(); ok {
		if err := department.LeaderEmailValidator(v); err != nil {
			return &ValidationError{Name: "leader_email", err: fmt.Errorf(`ent: validator failed for field "Department.leader_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Department.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Department.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := department.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Department.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DepartmentCreate) sqlSave(ctx context.Context) (*Department, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Department.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DepartmentCreate) createSpec() (*Department, *sqlgraph.CreateSpec) {
	var (
		_node = &Department{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(department.Table, sqlgraph.NewFieldSpec(department.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(department.FieldParentID, field.TypeString, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(department.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(department.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(department.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(department.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(department.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LeaderName(); ok {
		_spec.SetField(department.FieldLeaderName, field.TypeString, value)
		_node.LeaderName = value
	}
	if value, ok := _c.mutation.LeaderPhone(); ok {
		_spec.SetField(department.FieldLeaderPhone, field.TypeString, value)
		_node.LeaderPhone = value
	}
	if value, ok := _c.mutation.LeaderEmail(); ok {
		_spec.SetField(department.FieldLeaderEmail, field.TypeString, value)
		_node.LeaderEmail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(department.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(department.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(department.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// DepartmentCreateBulk is the builder for creating many Department entities in bulk.
type DepartmentCreateBulk struct {
	config
	err      error
	builders []*DepartmentCreate
}

// Save creates the Department entities in the database.
func (_c *DepartmentCreateBulk) Save(ctx context.Context) ([]*Department, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Department, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DepartmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DepartmentCreateBulk) SaveX(ctx context.Context) []*Department {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DepartmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DepartmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
