// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/dicttype"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/predicate"
)

// DictTypeUpdate is the builder for updating DictType entities.
type DictTypeUpdate struct {
	config
	hooks    []Hook
	mutation *DictTypeMutation
}

// Where appends a list predicates to the DictTypeUpdate builder.
func (_u *DictTypeUpdate) Where(ps ...predicate.DictType) *DictTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DictTypeUpdate) SetName(v string) *DictTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictTypeUpdate) SetNillableName(v *string) *DictTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *DictTypeUpdate) SetCode(v string) *DictTypeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DictTypeUpdate) SetNillableCode(v *string) *DictTypeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictTypeUpdate) SetStatus(v dicttype.Status) *DictTypeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictTypeUpdate) SetNillableStatus(v *dicttype.Status) *DictTypeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictTypeUpdate) SetRemark(v string) *DictTypeUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictTypeUpdate) SetNillableRemark(v *string) *DictTypeUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DictTypeUpdate) ClearRemark() *DictTypeUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictTypeUpdate) SetUpdatedAt(v time.Time) *DictTypeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictTypeUpdate) SetDeletedAt(v time.Time) *DictTypeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictTypeUpdate) SetNillableDeletedAt(v *time.Time) *DictTypeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictTypeUpdate) ClearDeletedAt() *DictTypeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the DictTypeMutation object of the builder.
func (_u *DictTypeUpdate) Mutation() *DictTypeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictTypeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictTypeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dicttype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dicttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := dicttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DictType.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := dicttype.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DictType.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := dicttype.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "DictType.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *DictTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dicttype.Table, dicttype.Columns, sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dicttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(dicttype.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dicttype.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dicttype.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dicttype.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dicttype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dicttype.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dicttype.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dicttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictTypeUpdateOne is the builder for updating a single DictType entity.
type DictTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictTypeMutation
}

// SetName sets the "name" field.
func (_u *DictTypeUpdateOne) SetName(v string) *DictTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DictTypeUpdateOne) SetNillableName(v *string) *DictTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *DictTypeUpdateOne) SetCode(v string) *DictTypeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *DictTypeUpdateOne) SetNillableCode(v *string) *DictTypeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictTypeUpdateOne) SetStatus(v dicttype.Status) *DictTypeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictTypeUpdateOne) SetNillableStatus(v *dicttype.Status) *DictTypeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictTypeUpdateOne) SetRemark(v string) *DictTypeUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictTypeUpdateOne) SetNillableRemark(v *string) *DictTypeUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *DictTypeUpdateOne) ClearRemark() *DictTypeUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictTypeUpdateOne) SetUpdatedAt(v time.Time) *DictTypeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictTypeUpdateOne) SetDeletedAt(v time.Time) *DictTypeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictTypeUpdateOne) SetNillableDeletedAt(v *time.Time) *DictTypeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictTypeUpdateOne) ClearDeletedAt() *DictTypeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the DictTypeMutation object of the builder.
func (_u *DictTypeUpdateOne) Mutation() *DictTypeMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictTypeUpdate builder.
func (_u *DictTypeUpdateOne) Where(ps ...predicate.DictType) *DictTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictTypeUpdateOne) Select(field string, fields ...string) *DictTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictType entity.
func (_u *DictTypeUpdateOne) Save(ctx context.Context) (*DictType, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictTypeUpdateOne) SaveX(ctx context.Context) *DictType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictTypeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dicttype.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dicttype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DictType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := dicttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "DictType.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := dicttype.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DictType.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := dicttype.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "DictType.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *DictTypeUpdateOne) sqlSave(ctx context.Context) (_node *DictType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dicttype.Table, dicttype.Columns, sqlgraph.NewFieldSpec(dicttype.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dicttype.FieldID)
		for _, f := range fields {
			if !dicttype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dicttype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dicttype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(dicttype.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dicttype.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dicttype.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(dicttype.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dicttype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dicttype.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dicttype.FieldDeletedAt, field.TypeTime)
	}
	_node = &DictType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dicttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
