// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/formschema"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// FormSchemaUpdate is the builder for updating FormSchema entities.
type FormSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *FormSchemaMutation
}

// Where appends a list predicates to the FormSchemaUpdate builder.
func (_u *FormSchemaUpdate) Where(ps ...predicate.FormSchema) *FormSchemaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FormSchemaUpdate) SetName(v string) *FormSchemaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableName(v *string) *FormSchemaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *FormSchemaUpdate) SetCode(v string) *FormSchemaUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableCode(v *string) *FormSchemaUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FormSchemaUpdate) SetDescription(v string) *FormSchemaUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableDescription(v *string) *FormSchemaUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FormSchemaUpdate) ClearDescription() *FormSchemaUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSchemaJSON sets the "schema_json" field.
func (_u *FormSchemaUpdate) SetSchemaJSON(v map[string]interface{}) *FormSchemaUpdate {
	_u.mutation.SetSchemaJSON(v)
	return _u
}

// ClearSchemaJSON clears the value of the "schema_json" field.
func (_u *FormSchemaUpdate) ClearSchemaJSON() *FormSchemaUpdate {
	_u.mutation.ClearSchemaJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FormSchemaUpdate) SetStatus(v formschema.Status) *FormSchemaUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableStatus(v *formschema.Status) *FormSchemaUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *FormSchemaUpdate) SetRemark(v string) *FormSchemaUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableRemark(v *string) *FormSchemaUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *FormSchemaUpdate) ClearRemark() *FormSchemaUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FormSchemaUpdate) SetUpdatedAt(v time.Time) *FormSchemaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FormSchemaUpdate) SetDeletedAt(v time.Time) *FormSchemaUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FormSchemaUpdate) SetNillableDeletedAt(v *time.Time) *FormSchemaUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FormSchemaUpdate) ClearDeletedAt() *FormSchemaUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the FormSchemaMutation object of the builder.
func (_u *FormSchemaUpdate) Mutation() *FormSchemaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FormSchemaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FormSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FormSchemaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FormSchemaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FormSchemaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := formschema.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FormSchemaUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := formschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FormSchema.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := formschema.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "FormSchema.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := formschema.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FormSchema.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := formschema.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FormSchema.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := formschema.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "FormSchema.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *FormSchemaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(formschema.Table, formschema.Columns, sqlgraph.NewFieldSpec(formschema.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(formschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(formschema.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(formschema.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(formschema.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SchemaJSON(); ok {
		_spec.SetField(formschema.FieldSchemaJSON, field.TypeJSON, value)
	}
	if _u.mutation.SchemaJSONCleared() {
		_spec.ClearField(formschema.FieldSchemaJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(formschema.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(formschema.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(formschema.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(formschema.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(formschema.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(formschema.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{formschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FormSchemaUpdateOne is the builder for updating a single FormSchema entity.
type FormSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FormSchemaMutation
}

// SetName sets the "name" field.
func (_u *FormSchemaUpdateOne) SetName(v string) *FormSchemaUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableName(v *string) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *FormSchemaUpdateOne) SetCode(v string) *FormSchemaUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableCode(v *string) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *FormSchemaUpdateOne) SetDescription(v string) *FormSchemaUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableDescription(v *string) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FormSchemaUpdateOne) ClearDescription() *FormSchemaUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSchemaJSON sets the "schema_json" field.
func (_u *FormSchemaUpdateOne) SetSchemaJSON(v map[string]interface{}) *FormSchemaUpdateOne {
	_u.mutation.SetSchemaJSON(v)
	return _u
}

// ClearSchemaJSON clears the value of the "schema_json" field.
func (_u *FormSchemaUpdateOne) ClearSchemaJSON() *FormSchemaUpdateOne {
	_u.mutation.ClearSchemaJSON()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FormSchemaUpdateOne) SetStatus(v formschema.Status) *FormSchemaUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableStatus(v *formschema.Status) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *FormSchemaUpdateOne) SetRemark(v string) *FormSchemaUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableRemark(v *string) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *FormSchemaUpdateOne) ClearRemark() *FormSchemaUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FormSchemaUpdateOne) SetUpdatedAt(v time.Time) *FormSchemaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FormSchemaUpdateOne) SetDeletedAt(v time.Time) *FormSchemaUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FormSchemaUpdateOne) SetNillableDeletedAt(v *time.Time) *FormSchemaUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FormSchemaUpdateOne) ClearDeletedAt() *FormSchemaUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the FormSchemaMutation object of the builder.
func (_u *FormSchemaUpdateOne) Mutation() *FormSchemaMutation {
	return _u.mutation
}

// Where appends a list predicates to the FormSchemaUpdate builder.
func (_u *FormSchemaUpdateOne) Where(ps ...predicate.FormSchema) *FormSchemaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FormSchemaUpdateOne) Select(field string, fields ...string) *FormSchemaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FormSchema entity.
func (_u *FormSchemaUpdateOne) Save(ctx context.Context) (*FormSchema, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FormSchemaUpdateOne) SaveX(ctx context.Context) *FormSchema {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FormSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FormSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FormSchemaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := formschema.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FormSchemaUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := formschema.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FormSchema.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := formschema.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "FormSchema.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := formschema.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "FormSchema.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := formschema.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FormSchema.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := formschema.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "FormSchema.remark": %w`, err)}
		}
	}
	return nil
}

func (_u *FormSchemaUpdateOne) sqlSave(ctx context.Context) (_node *FormSchema, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(formschema.Table, formschema.Columns, sqlgraph.NewFieldSpec(formschema.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FormSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, formschema.FieldID)
		for _, f := range fields {
			if !formschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != formschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(formschema.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(formschema.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(formschema.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(formschema.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SchemaJSON(); ok {
		_spec.SetField(formschema.FieldSchemaJSON, field.TypeJSON, value)
	}
	if _u.mutation.SchemaJSONCleared() {
		_spec.ClearField(formschema.FieldSchemaJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(formschema.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(formschema.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(formschema.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(formschema.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(formschema.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(formschema.FieldDeletedAt, field.TypeTime)
	}
	_node = &FormSchema{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{formschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
