// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/menuapipermission"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// MenuApiPermissionUpdate is the builder for updating MenuApiPermission entities.
type MenuApiPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *MenuApiPermissionMutation
}

// Where appends a list predicates to the MenuApiPermissionUpdate builder.
func (_u *MenuApiPermissionUpdate) Where(ps ...predicate.MenuApiPermission) *MenuApiPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMenuID sets the "menu_id" field.
func (_u *MenuApiPermissionUpdate) SetMenuID(v string) *MenuApiPermissionUpdate {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *MenuApiPermissionUpdate) SetNillableMenuID(v *string) *MenuApiPermissionUpdate {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetAPICode sets the "api_code" field.
func (_u *MenuApiPermissionUpdate) SetAPICode(v string) *MenuApiPermissionUpdate {
	_u.mutation.SetAPICode(v)
	return _u
}

// SetNillableAPICode sets the "api_code" field if the given value is not nil.
func (_u *MenuApiPermissionUpdate) SetNillableAPICode(v *string) *MenuApiPermissionUpdate {
	if v != nil {
		_u.SetAPICode(*v)
	}
	return _u
}

// Mutation returns the MenuApiPermissionMutation object of the builder.
func (_u *MenuApiPermissionUpdate) Mutation() *MenuApiPermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MenuApiPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuApiPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MenuApiPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuApiPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuApiPermissionUpdate) check() error {
	if v, ok := _u.mutation.MenuID(); ok {
		if err := menuapipermission.MenuIDValidator(v); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`ent: validator failed for field "MenuApiPermission.menu_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APICode(); ok {
		if err := menuapipermission.APICodeValidator(v); err != nil {
			return &ValidationError{Name: "api_code", err: fmt.Errorf(`ent: validator failed for field "MenuApiPermission.api_code": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuApiPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menuapipermission.Table, menuapipermission.Columns, sqlgraph.NewFieldSpec(menuapipermission.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(menuapipermission.FieldMenuID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APICode(); ok {
		_spec.SetField(menuapipermission.FieldAPICode, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuapipermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MenuApiPermissionUpdateOne is the builder for updating a single MenuApiPermission entity.
type MenuApiPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MenuApiPermissionMutation
}

// SetMenuID sets the "menu_id" field.
func (_u *MenuApiPermissionUpdateOne) SetMenuID(v string) *MenuApiPermissionUpdateOne {
	_u.mutation.SetMenuID(v)
	return _u
}

// SetNillableMenuID sets the "menu_id" field if the given value is not nil.
func (_u *MenuApiPermissionUpdateOne) SetNillableMenuID(v *string) *MenuApiPermissionUpdateOne {
	if v != nil {
		_u.SetMenuID(*v)
	}
	return _u
}

// SetAPICode sets the "api_code" field.
func (_u *MenuApiPermissionUpdateOne) SetAPICode(v string) *MenuApiPermissionUpdateOne {
	_u.mutation.SetAPICode(v)
	return _u
}

// SetNillableAPICode sets the "api_code" field if the given value is not nil.
func (_u *MenuApiPermissionUpdateOne) SetNillableAPICode(v *string) *MenuApiPermissionUpdateOne {
	if v != nil {
		_u.SetAPICode(*v)
	}
	return _u
}

// Mutation returns the MenuApiPermissionMutation object of the builder.
func (_u *MenuApiPermissionUpdateOne) Mutation() *MenuApiPermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the MenuApiPermissionUpdate builder.
func (_u *MenuApiPermissionUpdateOne) Where(ps ...predicate.MenuApiPermission) *MenuApiPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MenuApiPermissionUpdateOne) Select(field string, fields ...string) *MenuApiPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MenuApiPermission entity.
func (_u *MenuApiPermissionUpdateOne) Save(ctx context.Context) (*MenuApiPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuApiPermissionUpdateOne) SaveX(ctx context.Context) *MenuApiPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MenuApiPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuApiPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuApiPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.MenuID(); ok {
		if err := menuapipermission.MenuIDValidator(v); err != nil {
			return &ValidationError{Name: "menu_id", err: fmt.Errorf(`ent: validator failed for field "MenuApiPermission.menu_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APICode(); ok {
		if err := menuapipermission.APICodeValidator(v); err != nil {
			return &ValidationError{Name: "api_code", err: fmt.Errorf(`ent: validator failed for field "MenuApiPermission.api_code": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuApiPermissionUpdateOne) sqlSave(ctx context.Context) (_node *MenuApiPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menuapipermission.Table, menuapipermission.Columns, sqlgraph.NewFieldSpec(menuapipermission.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MenuApiPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menuapipermission.FieldID)
		for _, f := range fields {
			if !menuapipermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != menuapipermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MenuID(); ok {
		_spec.SetField(menuapipermission.FieldMenuID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APICode(); ok {
		_spec.SetField(menuapipermission.FieldAPICode, field.TypeString, value)
	}
	_node = &MenuApiPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menuapipermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
