// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/notification"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/notificationrecord"
)

// NotificationRecordCreate is the builder for creating a NotificationRecord entity.
type NotificationRecordCreate struct {
	config
	mutation *NotificationRecordMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *NotificationRecordCreate) SetTenantID(v string) *NotificationRecordCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableTenantID(v *string) *NotificationRecordCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetNotificationID sets the "notification_id" field.
func (_c *NotificationRecordCreate) SetNotificationID(v string) *NotificationRecordCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationRecordCreate) SetUserID(v string) *NotificationRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIsRead sets the "is_read" field.
func (_c *NotificationRecordCreate) SetIsRead(v bool) *NotificationRecordCreate {
	_c.mutation.SetIsRead(v)
	return _c
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableIsRead(v *bool) *NotificationRecordCreate {
	if v != nil {
		_c.SetIsRead(*v)
	}
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *NotificationRecordCreate) SetReadAt(v time.Time) *NotificationRecordCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableReadAt(v *time.Time) *NotificationRecordCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *NotificationRecordCreate) SetIsDeleted(v bool) *NotificationRecordCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableIsDeleted(v *bool) *NotificationRecordCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationRecordCreate) SetCreatedAt(v time.Time) *NotificationRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableCreatedAt(v *time.Time) *NotificationRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationRecordCreate) SetUpdatedAt(v time.Time) *NotificationRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationRecordCreate) SetNillableUpdatedAt(v *time.Time) *NotificationRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationRecordCreate) SetID(v string) *NotificationRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNotification sets the "notification" edge to the Notification entity.
func (_c *NotificationRecordCreate) SetNotification(v *Notification) *NotificationRecordCreate {
	return _c.SetNotificationID(v.ID)
}

// Mutation returns the NotificationRecordMutation object of the builder.
func (_c *NotificationRecordCreate) Mutation() *NotificationRecordMutation {
	return _c.mutation
}

// Save creates the NotificationRecord in the database.
func (_c *NotificationRecordCreate) Save(ctx context.Context) (*NotificationRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationRecordCreate) SaveX(ctx context.Context) *NotificationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationRecordCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := notificationrecord.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		v := notificationrecord.DefaultIsRead
		_c.mutation.SetIsRead(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := notificationrecord.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationRecordCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "NotificationRecord.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := notificationrecord.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "NotificationRecord.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "NotificationRecord.notification_id"`)}
	}
	if v, ok := _c.mutation.NotificationID(); ok {
		if err := notificationrecord.NotificationIDValidator(v); err != nil {
			return &ValidationError{Name: "notification_id", err: fmt.Errorf(`ent: validator failed for field "NotificationRecord.notification_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "NotificationRecord.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := notificationrecord.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotificationRecord.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsRead(); !ok {
		return &ValidationError{Name: "is_read", err: errors.New(`ent: missing required field "NotificationRecord.is_read"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "NotificationRecord.is_deleted"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationRecord.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := notificationrecord.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NotificationRecord.id": %w`, err)}
		}
	}
	if len(_c.mutation.NotificationIDs()) == 0 {
		return &ValidationError{Name: "notification", err: errors.New(`ent: missing required edge "NotificationRecord.notification"`)}
	}
	return nil
}

func (_c *NotificationRecordCreate) sqlSave(ctx context.Context) (*NotificationRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NotificationRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationRecordCreate) createSpec() (*NotificationRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationrecord.Table, sqlgraph.NewFieldSpec(notificationrecord.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(notificationrecord.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(notificationrecord.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.IsRead(); ok {
		_spec.SetField(notificationrecord.FieldIsRead, field.TypeBool, value)
		_node.IsRead = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(notificationrecord.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(notificationrecord.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationrecord.NotificationTable,
			Columns: []string{notificationrecord.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationRecordCreateBulk is the builder for creating many NotificationRecord entities in bulk.
type NotificationRecordCreateBulk struct {
	config
	err      error
	builders []*NotificationRecordCreate
}

// Save creates the NotificationRecord entities in the database.
func (_c *NotificationRecordCreateBulk) Save(ctx context.Context) ([]*NotificationRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationRecordCreateBulk) SaveX(ctx context.Context) []*NotificationRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
