// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/operationlog"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
)

// OperationLogUpdate is the builder for updating OperationLog entities.
type OperationLogUpdate struct {
	config
	hooks    []Hook
	mutation *OperationLogMutation
}

// Where appends a list predicates to the OperationLogUpdate builder.
func (_u *OperationLogUpdate) Where(ps ...predicate.OperationLog) *OperationLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *OperationLogUpdate) SetAdminID(v string) *OperationLogUpdate {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableAdminID(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *OperationLogUpdate) ClearAdminID() *OperationLogUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAdminName sets the "admin_name" field.
func (_u *OperationLogUpdate) SetAdminName(v string) *OperationLogUpdate {
	_u.mutation.SetAdminName(v)
	return _u
}

// SetNillableAdminName sets the "admin_name" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableAdminName(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetAdminName(*v)
	}
	return _u
}

// ClearAdminName clears the value of the "admin_name" field.
func (_u *OperationLogUpdate) ClearAdminName() *OperationLogUpdate {
	_u.mutation.ClearAdminName()
	return _u
}

// SetModule sets the "module" field.
func (_u *OperationLogUpdate) SetModule(v string) *OperationLogUpdate {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableModule(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// ClearModule clears the value of the "module" field.
func (_u *OperationLogUpdate) ClearModule() *OperationLogUpdate {
	_u.mutation.ClearModule()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *OperationLogUpdate) SetOperation(v string) *OperationLogUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableOperation(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *OperationLogUpdate) ClearOperation() *OperationLogUpdate {
	_u.mutation.ClearOperation()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OperationLogUpdate) SetMethod(v string) *OperationLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableMethod(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OperationLogUpdate) ClearMethod() *OperationLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *OperationLogUpdate) SetPath(v string) *OperationLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillablePath(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OperationLogUpdate) ClearPath() *OperationLogUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *OperationLogUpdate) SetSummary(v string) *OperationLogUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableSummary(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *OperationLogUpdate) ClearSummary() *OperationLogUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetIP sets the "ip" field.
func (_u *OperationLogUpdate) SetIP(v string) *OperationLogUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableIP(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *OperationLogUpdate) ClearIP() *OperationLogUpdate {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OperationLogUpdate) SetUserAgent(v string) *OperationLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableUserAgent(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OperationLogUpdate) ClearUserAgent() *OperationLogUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetParams sets the "params" field.
func (_u *OperationLogUpdate) SetParams(v string) *OperationLogUpdate {
	_u.mutation.SetParams(v)
	return _u
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableParams(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetParams(*v)
	}
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *OperationLogUpdate) ClearParams() *OperationLogUpdate {
	_u.mutation.ClearParams()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OperationLogUpdate) SetStatus(v operationlog.Status) *OperationLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableStatus(v *operationlog.Status) *OperationLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *OperationLogUpdate) SetCode(v string) *OperationLogUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableCode(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *OperationLogUpdate) ClearCode() *OperationLogUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetMessage sets the "message" field.
func (_u *OperationLogUpdate) SetMessage(v string) *OperationLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableMessage(v *string) *OperationLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *OperationLogUpdate) ClearMessage() *OperationLogUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetCostMs sets the "cost_ms" field.
func (_u *OperationLogUpdate) SetCostMs(v int) *OperationLogUpdate {
	_u.mutation.ResetCostMs()
	_u.mutation.SetCostMs(v)
	return _u
}

// SetNillableCostMs sets the "cost_ms" field if the given value is not nil.
func (_u *OperationLogUpdate) SetNillableCostMs(v *int) *OperationLogUpdate {
	if v != nil {
		_u.SetCostMs(*v)
	}
	return _u
}

// AddCostMs adds value to the "cost_ms" field.
func (_u *OperationLogUpdate) AddCostMs(v int) *OperationLogUpdate {
	_u.mutation.AddCostMs(v)
	return _u
}

// Mutation returns the OperationLogMutation object of the builder.
func (_u *OperationLogUpdate) Mutation() *OperationLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OperationLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OperationLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperationLogUpdate) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := operationlog.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "OperationLog.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminName(); ok {
		if err := operationlog.AdminNameValidator(v); err != nil {
			return &ValidationError{Name: "admin_name", err: fmt.Errorf(`ent: validator failed for field "OperationLog.admin_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Module(); ok {
		if err := operationlog.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "OperationLog.module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := operationlog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "OperationLog.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := operationlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OperationLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := operationlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OperationLog.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := operationlog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "OperationLog.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := operationlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "OperationLog.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := operationlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OperationLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := operationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OperationLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := operationlog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OperationLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := operationlog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "OperationLog.message": %w`, err)}
		}
	}
	return nil
}

func (_u *OperationLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operationlog.Table, operationlog.Columns, sqlgraph.NewFieldSpec(operationlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(operationlog.FieldAdminID, field.TypeString, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(operationlog.FieldAdminID, field.TypeString)
	}
	if value, ok := _u.mutation.AdminName(); ok {
		_spec.SetField(operationlog.FieldAdminName, field.TypeString, value)
	}
	if _u.mutation.AdminNameCleared() {
		_spec.ClearField(operationlog.FieldAdminName, field.TypeString)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(operationlog.FieldModule, field.TypeString, value)
	}
	if _u.mutation.ModuleCleared() {
		_spec.ClearField(operationlog.FieldModule, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(operationlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(operationlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(operationlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(operationlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(operationlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(operationlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(operationlog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(operationlog.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(operationlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(operationlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(operationlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(operationlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(operationlog.FieldParams, field.TypeString, value)
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(operationlog.FieldParams, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(operationlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(operationlog.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(operationlog.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(operationlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(operationlog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CostMs(); ok {
		_spec.SetField(operationlog.FieldCostMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostMs(); ok {
		_spec.AddField(operationlog.FieldCostMs, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OperationLogUpdateOne is the builder for updating a single OperationLog entity.
type OperationLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OperationLogMutation
}

// SetAdminID sets the "admin_id" field.
func (_u *OperationLogUpdateOne) SetAdminID(v string) *OperationLogUpdateOne {
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableAdminID(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *OperationLogUpdateOne) ClearAdminID() *OperationLogUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetAdminName sets the "admin_name" field.
func (_u *OperationLogUpdateOne) SetAdminName(v string) *OperationLogUpdateOne {
	_u.mutation.SetAdminName(v)
	return _u
}

// SetNillableAdminName sets the "admin_name" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableAdminName(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetAdminName(*v)
	}
	return _u
}

// ClearAdminName clears the value of the "admin_name" field.
func (_u *OperationLogUpdateOne) ClearAdminName() *OperationLogUpdateOne {
	_u.mutation.ClearAdminName()
	return _u
}

// SetModule sets the "module" field.
func (_u *OperationLogUpdateOne) SetModule(v string) *OperationLogUpdateOne {
	_u.mutation.SetModule(v)
	return _u
}

// SetNillableModule sets the "module" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableModule(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetModule(*v)
	}
	return _u
}

// ClearModule clears the value of the "module" field.
func (_u *OperationLogUpdateOne) ClearModule() *OperationLogUpdateOne {
	_u.mutation.ClearModule()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *OperationLogUpdateOne) SetOperation(v string) *OperationLogUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableOperation(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// ClearOperation clears the value of the "operation" field.
func (_u *OperationLogUpdateOne) ClearOperation() *OperationLogUpdateOne {
	_u.mutation.ClearOperation()
	return _u
}

// SetMethod sets the "method" field.
func (_u *OperationLogUpdateOne) SetMethod(v string) *OperationLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableMethod(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *OperationLogUpdateOne) ClearMethod() *OperationLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *OperationLogUpdateOne) SetPath(v string) *OperationLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillablePath(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *OperationLogUpdateOne) ClearPath() *OperationLogUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *OperationLogUpdateOne) SetSummary(v string) *OperationLogUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableSummary(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *OperationLogUpdateOne) ClearSummary() *OperationLogUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetIP sets the "ip" field.
func (_u *OperationLogUpdateOne) SetIP(v string) *OperationLogUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableIP(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// ClearIP clears the value of the "ip" field.
func (_u *OperationLogUpdateOne) ClearIP() *OperationLogUpdateOne {
	_u.mutation.ClearIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *OperationLogUpdateOne) SetUserAgent(v string) *OperationLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableUserAgent(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *OperationLogUpdateOne) ClearUserAgent() *OperationLogUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetParams sets the "params" field.
func (_u *OperationLogUpdateOne) SetParams(v string) *OperationLogUpdateOne {
	_u.mutation.SetParams(v)
	return _u
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableParams(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetParams(*v)
	}
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *OperationLogUpdateOne) ClearParams() *OperationLogUpdateOne {
	_u.mutation.ClearParams()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OperationLogUpdateOne) SetStatus(v operationlog.Status) *OperationLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableStatus(v *operationlog.Status) *OperationLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *OperationLogUpdateOne) SetCode(v string) *OperationLogUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableCode(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *OperationLogUpdateOne) ClearCode() *OperationLogUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetMessage sets the "message" field.
func (_u *OperationLogUpdateOne) SetMessage(v string) *OperationLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableMessage(v *string) *OperationLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *OperationLogUpdateOne) ClearMessage() *OperationLogUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetCostMs sets the "cost_ms" field.
func (_u *OperationLogUpdateOne) SetCostMs(v int) *OperationLogUpdateOne {
	_u.mutation.ResetCostMs()
	_u.mutation.SetCostMs(v)
	return _u
}

// SetNillableCostMs sets the "cost_ms" field if the given value is not nil.
func (_u *OperationLogUpdateOne) SetNillableCostMs(v *int) *OperationLogUpdateOne {
	if v != nil {
		_u.SetCostMs(*v)
	}
	return _u
}

// AddCostMs adds value to the "cost_ms" field.
func (_u *OperationLogUpdateOne) AddCostMs(v int) *OperationLogUpdateOne {
	_u.mutation.AddCostMs(v)
	return _u
}

// Mutation returns the OperationLogMutation object of the builder.
func (_u *OperationLogUpdateOne) Mutation() *OperationLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the OperationLogUpdate builder.
func (_u *OperationLogUpdateOne) Where(ps ...predicate.OperationLog) *OperationLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OperationLogUpdateOne) Select(field string, fields ...string) *OperationLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OperationLog entity.
func (_u *OperationLogUpdateOne) Save(ctx context.Context) (*OperationLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OperationLogUpdateOne) SaveX(ctx context.Context) *OperationLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OperationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OperationLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OperationLogUpdateOne) check() error {
	if v, ok := _u.mutation.AdminID(); ok {
		if err := operationlog.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "OperationLog.admin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminName(); ok {
		if err := operationlog.AdminNameValidator(v); err != nil {
			return &ValidationError{Name: "admin_name", err: fmt.Errorf(`ent: validator failed for field "OperationLog.admin_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Module(); ok {
		if err := operationlog.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "OperationLog.module": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := operationlog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "OperationLog.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := operationlog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "OperationLog.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := operationlog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "OperationLog.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := operationlog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "OperationLog.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IP(); ok {
		if err := operationlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "OperationLog.ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := operationlog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "OperationLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := operationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OperationLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := operationlog.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OperationLog.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := operationlog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "OperationLog.message": %w`, err)}
		}
	}
	return nil
}

func (_u *OperationLogUpdateOne) sqlSave(ctx context.Context) (_node *OperationLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(operationlog.Table, operationlog.Columns, sqlgraph.NewFieldSpec(operationlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OperationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, operationlog.FieldID)
		for _, f := range fields {
			if !operationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != operationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(operationlog.FieldAdminID, field.TypeString, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(operationlog.FieldAdminID, field.TypeString)
	}
	if value, ok := _u.mutation.AdminName(); ok {
		_spec.SetField(operationlog.FieldAdminName, field.TypeString, value)
	}
	if _u.mutation.AdminNameCleared() {
		_spec.ClearField(operationlog.FieldAdminName, field.TypeString)
	}
	if value, ok := _u.mutation.Module(); ok {
		_spec.SetField(operationlog.FieldModule, field.TypeString, value)
	}
	if _u.mutation.ModuleCleared() {
		_spec.ClearField(operationlog.FieldModule, field.TypeString)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(operationlog.FieldOperation, field.TypeString, value)
	}
	if _u.mutation.OperationCleared() {
		_spec.ClearField(operationlog.FieldOperation, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(operationlog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(operationlog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(operationlog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(operationlog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(operationlog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(operationlog.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(operationlog.FieldIP, field.TypeString, value)
	}
	if _u.mutation.IPCleared() {
		_spec.ClearField(operationlog.FieldIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(operationlog.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(operationlog.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(operationlog.FieldParams, field.TypeString, value)
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(operationlog.FieldParams, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(operationlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(operationlog.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(operationlog.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(operationlog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(operationlog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CostMs(); ok {
		_spec.SetField(operationlog.FieldCostMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostMs(); ok {
		_spec.AddField(operationlog.FieldCostMs, field.TypeInt, value)
	}
	_node = &OperationLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{operationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
