// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/operationlog"
)

// 操作日志表
type OperationLog struct {
	config `json:"-"`
	// ID of the ent.
	// 日志ID
	ID string `json:"id,omitempty"`
	// 租户ID
	TenantID string `json:"tenant_id,omitempty"`
	// 操作人ID（未登录操作为空）
	AdminID string `json:"admin_id,omitempty"`
	// 操作人姓名（冗余，避免联表）
	AdminName string `json:"admin_name,omitempty"`
	// 所属模块/服务名，如 Admin、Dictionary
	Module string `json:"module,omitempty"`
	// 操作名，如 CreateAdmin
	Operation string `json:"operation,omitempty"`
	// HTTP 方法
	Method string `json:"method,omitempty"`
	// 请求路径
	Path string `json:"path,omitempty"`
	// 接口中文摘要（来自 OpenAPI）
	Summary string `json:"summary,omitempty"`
	// 来源IP
	IP string `json:"ip,omitempty"`
	// 客户端 UA
	UserAgent string `json:"user_agent,omitempty"`
	// 请求参数（JSON，已脱敏并截断）
	Params string `json:"params,omitempty"`
	// 结果：success=成功 fail=失败
	Status operationlog.Status `json:"status,omitempty"`
	// 失败时的错误码
	Code string `json:"code,omitempty"`
	// 失败时的错误信息
	Message string `json:"message,omitempty"`
	// 耗时（毫秒）
	CostMs int `json:"cost_ms,omitempty"`
	// 操作时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OperationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldCostMs:
			values[i] = new(sql.NullInt64)
		case operationlog.FieldID, operationlog.FieldTenantID, operationlog.FieldAdminID, operationlog.FieldAdminName, operationlog.FieldModule, operationlog.FieldOperation, operationlog.FieldMethod, operationlog.FieldPath, operationlog.FieldSummary, operationlog.FieldIP, operationlog.FieldUserAgent, operationlog.FieldParams, operationlog.FieldStatus, operationlog.FieldCode, operationlog.FieldMessage:
			values[i] = new(sql.NullString)
		case operationlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OperationLog fields.
func (_m *OperationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case operationlog.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case operationlog.FieldAdminID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = value.String
			}
		case operationlog.FieldAdminName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_name", values[i])
			} else if value.Valid {
				_m.AdminName = value.String
			}
		case operationlog.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = value.String
			}
		case operationlog.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case operationlog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case operationlog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case operationlog.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case operationlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case operationlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case operationlog.FieldParams:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value.Valid {
				_m.Params = value.String
			}
		case operationlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = operationlog.Status(value.String)
			}
		case operationlog.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case operationlog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case operationlog.FieldCostMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_ms", values[i])
			} else if value.Valid {
				_m.CostMs = int(value.Int64)
			}
		case operationlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OperationLog.
// This includes values selected through modifiers, order, etc.
func (_m *OperationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OperationLog.
// Note that you need to call OperationLog.Unwrap() before calling this method if this OperationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OperationLog) Update() *OperationLogUpdateOne {
	return NewOperationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OperationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OperationLog) Unwrap() *OperationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OperationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OperationLog) String() string {
	var builder strings.Builder
	builder.WriteString("OperationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("admin_id=")
	builder.WriteString(_m.AdminID)
	builder.WriteString(", ")
	builder.WriteString("admin_name=")
	builder.WriteString(_m.AdminName)
	builder.WriteString(", ")
	builder.WriteString("module=")
	builder.WriteString(_m.Module)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(_m.Params)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("cost_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.CostMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OperationLogs is a parsable slice of OperationLog.
type OperationLogs []*OperationLog
