// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/admin"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/adminrole"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/menu"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/predicate"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/role"
	"github.com/antsurge/weaver-admin/app/admin/service/internal/data/ent/rolemenu"
)

// RoleUpdate is the builder for updating Role entities.
type RoleUpdate struct {
	config
	hooks    []Hook
	mutation *RoleMutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdate) Where(ps ...predicate.Role) *RoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RoleUpdate) SetName(v string) *RoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableName(v *string) *RoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *RoleUpdate) SetCode(v string) *RoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableCode(v *string) *RoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *RoleUpdate) SetWeight(v int) *RoleUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableWeight(v *int) *RoleUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *RoleUpdate) AddWeight(v int) *RoleUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoleUpdate) SetStatus(v role.Status) *RoleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStatus(v *role.Status) *RoleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *RoleUpdate) SetRemark(v string) *RoleUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableRemark(v *string) *RoleUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *RoleUpdate) ClearRemark() *RoleUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *RoleUpdate) SetIsSystem(v bool) *RoleUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableIsSystem(v *bool) *RoleUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetDataScope sets the "data_scope" field.
func (_u *RoleUpdate) SetDataScope(v string) *RoleUpdate {
	_u.mutation.SetDataScope(v)
	return _u
}

// SetNillableDataScope sets the "data_scope" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableDataScope(v *string) *RoleUpdate {
	if v != nil {
		_u.SetDataScope(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RoleUpdate) SetCreatedAt(v time.Time) *RoleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableCreatedAt(v *time.Time) *RoleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoleUpdate) SetUpdatedAt(v time.Time) *RoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RoleUpdate) SetDeletedAt(v time.Time) *RoleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableDeletedAt(v *time.Time) *RoleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RoleUpdate) ClearDeletedAt() *RoleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *RoleUpdate) AddMenuIDs(ids ...string) *RoleUpdate {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *RoleUpdate) AddMenus(v ...*Menu) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the Admin entity by IDs.
func (_u *RoleUpdate) AddAdminIDs(ids ...string) *RoleUpdate {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the Admin entity.
func (_u *RoleUpdate) AddAdmins(v ...*Admin) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddRoleMenuIDs adds the "role_menus" edge to the RoleMenu entity by IDs.
func (_u *RoleUpdate) AddRoleMenuIDs(ids ...string) *RoleUpdate {
	_u.mutation.AddRoleMenuIDs(ids...)
	return _u
}

// AddRoleMenus adds the "role_menus" edges to the RoleMenu entity.
func (_u *RoleUpdate) AddRoleMenus(v ...*RoleMenu) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleMenuIDs(ids...)
}

// AddAdminRoleIDs adds the "admin_roles" edge to the AdminRole entity by IDs.
func (_u *RoleUpdate) AddAdminRoleIDs(ids ...string) *RoleUpdate {
	_u.mutation.AddAdminRoleIDs(ids...)
	return _u
}

// AddAdminRoles adds the "admin_roles" edges to the AdminRole entity.
func (_u *RoleUpdate) AddAdminRoles(v ...*AdminRole) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminRoleIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdate) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *RoleUpdate) ClearMenus() *RoleUpdate {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *RoleUpdate) RemoveMenuIDs(ids ...string) *RoleUpdate {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *RoleUpdate) RemoveMenus(v ...*Menu) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the Admin entity.
func (_u *RoleUpdate) ClearAdmins() *RoleUpdate {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to Admin entities by IDs.
func (_u *RoleUpdate) RemoveAdminIDs(ids ...string) *RoleUpdate {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to Admin entities.
func (_u *RoleUpdate) RemoveAdmins(v ...*Admin) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearRoleMenus clears all "role_menus" edges to the RoleMenu entity.
func (_u *RoleUpdate) ClearRoleMenus() *RoleUpdate {
	_u.mutation.ClearRoleMenus()
	return _u
}

// RemoveRoleMenuIDs removes the "role_menus" edge to RoleMenu entities by IDs.
func (_u *RoleUpdate) RemoveRoleMenuIDs(ids ...string) *RoleUpdate {
	_u.mutation.RemoveRoleMenuIDs(ids...)
	return _u
}

// RemoveRoleMenus removes "role_menus" edges to RoleMenu entities.
func (_u *RoleUpdate) RemoveRoleMenus(v ...*RoleMenu) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleMenuIDs(ids...)
}

// ClearAdminRoles clears all "admin_roles" edges to the AdminRole entity.
func (_u *RoleUpdate) ClearAdminRoles() *RoleUpdate {
	_u.mutation.ClearAdminRoles()
	return _u
}

// RemoveAdminRoleIDs removes the "admin_roles" edge to AdminRole entities by IDs.
func (_u *RoleUpdate) RemoveAdminRoleIDs(ids ...string) *RoleUpdate {
	_u.mutation.RemoveAdminRoleIDs(ids...)
	return _u
}

// RemoveAdminRoles removes "admin_roles" edges to AdminRole entities.
func (_u *RoleUpdate) RemoveAdminRoles(v ...*AdminRole) *RoleUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminRoleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := role.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := role.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Role.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(role.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(role.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(role.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(role.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(role.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(role.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(role.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DataScope(); ok {
		_spec.SetField(role.FieldDataScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(role.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(role.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(role.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(role.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleMenusIDs(); len(nodes) > 0 && !_u.mutation.RoleMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminRolesIDs(); len(nodes) > 0 && !_u.mutation.AdminRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoleUpdateOne is the builder for updating a single Role entity.
type RoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleMutation
}

// SetName sets the "name" field.
func (_u *RoleUpdateOne) SetName(v string) *RoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableName(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *RoleUpdateOne) SetCode(v string) *RoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableCode(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *RoleUpdateOne) SetWeight(v int) *RoleUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableWeight(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *RoleUpdateOne) AddWeight(v int) *RoleUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoleUpdateOne) SetStatus(v role.Status) *RoleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStatus(v *role.Status) *RoleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *RoleUpdateOne) SetRemark(v string) *RoleUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableRemark(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *RoleUpdateOne) ClearRemark() *RoleUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *RoleUpdateOne) SetIsSystem(v bool) *RoleUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableIsSystem(v *bool) *RoleUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetDataScope sets the "data_scope" field.
func (_u *RoleUpdateOne) SetDataScope(v string) *RoleUpdateOne {
	_u.mutation.SetDataScope(v)
	return _u
}

// SetNillableDataScope sets the "data_scope" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableDataScope(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetDataScope(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RoleUpdateOne) SetCreatedAt(v time.Time) *RoleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableCreatedAt(v *time.Time) *RoleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoleUpdateOne) SetUpdatedAt(v time.Time) *RoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RoleUpdateOne) SetDeletedAt(v time.Time) *RoleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableDeletedAt(v *time.Time) *RoleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RoleUpdateOne) ClearDeletedAt() *RoleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddMenuIDs adds the "menus" edge to the Menu entity by IDs.
func (_u *RoleUpdateOne) AddMenuIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.AddMenuIDs(ids...)
	return _u
}

// AddMenus adds the "menus" edges to the Menu entity.
func (_u *RoleUpdateOne) AddMenus(v ...*Menu) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMenuIDs(ids...)
}

// AddAdminIDs adds the "admins" edge to the Admin entity by IDs.
func (_u *RoleUpdateOne) AddAdminIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.AddAdminIDs(ids...)
	return _u
}

// AddAdmins adds the "admins" edges to the Admin entity.
func (_u *RoleUpdateOne) AddAdmins(v ...*Admin) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminIDs(ids...)
}

// AddRoleMenuIDs adds the "role_menus" edge to the RoleMenu entity by IDs.
func (_u *RoleUpdateOne) AddRoleMenuIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.AddRoleMenuIDs(ids...)
	return _u
}

// AddRoleMenus adds the "role_menus" edges to the RoleMenu entity.
func (_u *RoleUpdateOne) AddRoleMenus(v ...*RoleMenu) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleMenuIDs(ids...)
}

// AddAdminRoleIDs adds the "admin_roles" edge to the AdminRole entity by IDs.
func (_u *RoleUpdateOne) AddAdminRoleIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.AddAdminRoleIDs(ids...)
	return _u
}

// AddAdminRoles adds the "admin_roles" edges to the AdminRole entity.
func (_u *RoleUpdateOne) AddAdminRoles(v ...*AdminRole) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAdminRoleIDs(ids...)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdateOne) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearMenus clears all "menus" edges to the Menu entity.
func (_u *RoleUpdateOne) ClearMenus() *RoleUpdateOne {
	_u.mutation.ClearMenus()
	return _u
}

// RemoveMenuIDs removes the "menus" edge to Menu entities by IDs.
func (_u *RoleUpdateOne) RemoveMenuIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.RemoveMenuIDs(ids...)
	return _u
}

// RemoveMenus removes "menus" edges to Menu entities.
func (_u *RoleUpdateOne) RemoveMenus(v ...*Menu) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMenuIDs(ids...)
}

// ClearAdmins clears all "admins" edges to the Admin entity.
func (_u *RoleUpdateOne) ClearAdmins() *RoleUpdateOne {
	_u.mutation.ClearAdmins()
	return _u
}

// RemoveAdminIDs removes the "admins" edge to Admin entities by IDs.
func (_u *RoleUpdateOne) RemoveAdminIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.RemoveAdminIDs(ids...)
	return _u
}

// RemoveAdmins removes "admins" edges to Admin entities.
func (_u *RoleUpdateOne) RemoveAdmins(v ...*Admin) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminIDs(ids...)
}

// ClearRoleMenus clears all "role_menus" edges to the RoleMenu entity.
func (_u *RoleUpdateOne) ClearRoleMenus() *RoleUpdateOne {
	_u.mutation.ClearRoleMenus()
	return _u
}

// RemoveRoleMenuIDs removes the "role_menus" edge to RoleMenu entities by IDs.
func (_u *RoleUpdateOne) RemoveRoleMenuIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.RemoveRoleMenuIDs(ids...)
	return _u
}

// RemoveRoleMenus removes "role_menus" edges to RoleMenu entities.
func (_u *RoleUpdateOne) RemoveRoleMenus(v ...*RoleMenu) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleMenuIDs(ids...)
}

// ClearAdminRoles clears all "admin_roles" edges to the AdminRole entity.
func (_u *RoleUpdateOne) ClearAdminRoles() *RoleUpdateOne {
	_u.mutation.ClearAdminRoles()
	return _u
}

// RemoveAdminRoleIDs removes the "admin_roles" edge to AdminRole entities by IDs.
func (_u *RoleUpdateOne) RemoveAdminRoleIDs(ids ...string) *RoleUpdateOne {
	_u.mutation.RemoveAdminRoleIDs(ids...)
	return _u
}

// RemoveAdminRoles removes "admin_roles" edges to AdminRole entities.
func (_u *RoleUpdateOne) RemoveAdminRoles(v ...*AdminRole) *RoleUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAdminRoleIDs(ids...)
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdateOne) Where(ps ...predicate.Role) *RoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoleUpdateOne) Select(field string, fields ...string) *RoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Role entity.
func (_u *RoleUpdateOne) Save(ctx context.Context) (*Role, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdateOne) SaveX(ctx context.Context) *Role {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := role.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := role.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Role.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RoleUpdateOne) sqlSave(ctx context.Context) (_node *Role, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Role.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role.FieldID)
		for _, f := range fields {
			if !role.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != role.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(role.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(role.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(role.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(role.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(role.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(role.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(role.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DataScope(); ok {
		_spec.SetField(role.FieldDataScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(role.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(role.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(role.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(role.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMenusIDs(); len(nodes) > 0 && !_u.mutation.MenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   role.MenusTable,
			Columns: role.MenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &RoleMenuCreate{config: _u.config, mutation: newRoleMenuMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !_u.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   role.AdminsTable,
			Columns: role.AdminsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &AdminRoleCreate{config: _u.config, mutation: newAdminRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoleMenusIDs(); len(nodes) > 0 && !_u.mutation.RoleMenusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.RoleMenusTable,
			Columns: []string{role.RoleMenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolemenu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAdminRolesIDs(); len(nodes) > 0 && !_u.mutation.AdminRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   role.AdminRolesTable,
			Columns: []string{role.AdminRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Role{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
