// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/admin"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/adminrole"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/department"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/dictdata"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/dicttype"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/permission"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/position"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/role"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/rolepermission"
	"github.com/hypercoze/kratos-admin/app/admin/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescRealName is the schema descriptor for real_name field.
	adminDescRealName := adminFields[1].Descriptor()
	// admin.DefaultRealName holds the default value on creation for the real_name field.
	admin.DefaultRealName = adminDescRealName.Default.(string)
	// adminDescCreateTime is the schema descriptor for create_time field.
	adminDescCreateTime := adminFields[7].Descriptor()
	// admin.DefaultCreateTime holds the default value on creation for the create_time field.
	admin.DefaultCreateTime = adminDescCreateTime.Default.(func() time.Time)
	// adminDescUpdateTime is the schema descriptor for update_time field.
	adminDescUpdateTime := adminFields[8].Descriptor()
	// admin.DefaultUpdateTime holds the default value on creation for the update_time field.
	admin.DefaultUpdateTime = adminDescUpdateTime.Default.(func() time.Time)
	// admin.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	admin.UpdateDefaultUpdateTime = adminDescUpdateTime.UpdateDefault.(func() time.Time)
	adminroleFields := schema.AdminRole{}.Fields()
	_ = adminroleFields
	// adminroleDescAdminID is the schema descriptor for admin_id field.
	adminroleDescAdminID := adminroleFields[1].Descriptor()
	// adminrole.AdminIDValidator is a validator for the "admin_id" field. It is called by the builders before save.
	adminrole.AdminIDValidator = adminroleDescAdminID.Validators[0].(func(string) error)
	// adminroleDescRoleID is the schema descriptor for role_id field.
	adminroleDescRoleID := adminroleFields[2].Descriptor()
	// adminrole.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	adminrole.RoleIDValidator = adminroleDescRoleID.Validators[0].(func(string) error)
	// adminroleDescCreatedAt is the schema descriptor for created_at field.
	adminroleDescCreatedAt := adminroleFields[3].Descriptor()
	// adminrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminrole.DefaultCreatedAt = adminroleDescCreatedAt.Default.(func() time.Time)
	// adminroleDescID is the schema descriptor for id field.
	adminroleDescID := adminroleFields[0].Descriptor()
	// adminrole.IDValidator is a validator for the "id" field. It is called by the builders before save.
	adminrole.IDValidator = adminroleDescID.Validators[0].(func(string) error)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescParentID is the schema descriptor for parent_id field.
	departmentDescParentID := departmentFields[1].Descriptor()
	// department.DefaultParentID holds the default value on creation for the parent_id field.
	department.DefaultParentID = departmentDescParentID.Default.(string)
	// departmentDescName is the schema descriptor for name field.
	departmentDescName := departmentFields[2].Descriptor()
	// department.NameValidator is a validator for the "name" field. It is called by the builders before save.
	department.NameValidator = func() func(string) error {
		validators := departmentDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// departmentDescCode is the schema descriptor for code field.
	departmentDescCode := departmentFields[3].Descriptor()
	// department.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	department.CodeValidator = func() func(string) error {
		validators := departmentDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// departmentDescWeight is the schema descriptor for weight field.
	departmentDescWeight := departmentFields[4].Descriptor()
	// department.DefaultWeight holds the default value on creation for the weight field.
	department.DefaultWeight = departmentDescWeight.Default.(int)
	// departmentDescLeaderName is the schema descriptor for leader_name field.
	departmentDescLeaderName := departmentFields[6].Descriptor()
	// department.LeaderNameValidator is a validator for the "leader_name" field. It is called by the builders before save.
	department.LeaderNameValidator = departmentDescLeaderName.Validators[0].(func(string) error)
	// departmentDescLeaderPhone is the schema descriptor for leader_phone field.
	departmentDescLeaderPhone := departmentFields[7].Descriptor()
	// department.LeaderPhoneValidator is a validator for the "leader_phone" field. It is called by the builders before save.
	department.LeaderPhoneValidator = departmentDescLeaderPhone.Validators[0].(func(string) error)
	// departmentDescLeaderEmail is the schema descriptor for leader_email field.
	departmentDescLeaderEmail := departmentFields[8].Descriptor()
	// department.LeaderEmailValidator is a validator for the "leader_email" field. It is called by the builders before save.
	department.LeaderEmailValidator = departmentDescLeaderEmail.Validators[0].(func(string) error)
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentFields[9].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentFields[10].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentFields[0].Descriptor()
	// department.IDValidator is a validator for the "id" field. It is called by the builders before save.
	department.IDValidator = departmentDescID.Validators[0].(func(string) error)
	dictdataFields := schema.DictData{}.Fields()
	_ = dictdataFields
	// dictdataDescDictTypeID is the schema descriptor for dict_type_id field.
	dictdataDescDictTypeID := dictdataFields[1].Descriptor()
	// dictdata.DictTypeIDValidator is a validator for the "dict_type_id" field. It is called by the builders before save.
	dictdata.DictTypeIDValidator = func() func(string) error {
		validators := dictdataDescDictTypeID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dict_type_id string) error {
			for _, fn := range fns {
				if err := fn(dict_type_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictdataDescLabel is the schema descriptor for label field.
	dictdataDescLabel := dictdataFields[2].Descriptor()
	// dictdata.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	dictdata.LabelValidator = func() func(string) error {
		validators := dictdataDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictdataDescValue is the schema descriptor for value field.
	dictdataDescValue := dictdataFields[3].Descriptor()
	// dictdata.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	dictdata.ValueValidator = func() func(string) error {
		validators := dictdataDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictdataDescWeight is the schema descriptor for weight field.
	dictdataDescWeight := dictdataFields[4].Descriptor()
	// dictdata.DefaultWeight holds the default value on creation for the weight field.
	dictdata.DefaultWeight = dictdataDescWeight.Default.(int)
	// dictdataDescRemark is the schema descriptor for remark field.
	dictdataDescRemark := dictdataFields[7].Descriptor()
	// dictdata.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	dictdata.RemarkValidator = dictdataDescRemark.Validators[0].(func(string) error)
	// dictdataDescCreatedAt is the schema descriptor for created_at field.
	dictdataDescCreatedAt := dictdataFields[8].Descriptor()
	// dictdata.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictdata.DefaultCreatedAt = dictdataDescCreatedAt.Default.(func() time.Time)
	// dictdataDescUpdatedAt is the schema descriptor for updated_at field.
	dictdataDescUpdatedAt := dictdataFields[9].Descriptor()
	// dictdata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictdata.DefaultUpdatedAt = dictdataDescUpdatedAt.Default.(func() time.Time)
	// dictdata.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictdata.UpdateDefaultUpdatedAt = dictdataDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictdataDescID is the schema descriptor for id field.
	dictdataDescID := dictdataFields[0].Descriptor()
	// dictdata.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dictdata.IDValidator = dictdataDescID.Validators[0].(func(string) error)
	dicttypeFields := schema.DictType{}.Fields()
	_ = dicttypeFields
	// dicttypeDescName is the schema descriptor for name field.
	dicttypeDescName := dicttypeFields[1].Descriptor()
	// dicttype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	dicttype.NameValidator = func() func(string) error {
		validators := dicttypeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dicttypeDescCode is the schema descriptor for code field.
	dicttypeDescCode := dicttypeFields[2].Descriptor()
	// dicttype.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	dicttype.CodeValidator = func() func(string) error {
		validators := dicttypeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dicttypeDescRemark is the schema descriptor for remark field.
	dicttypeDescRemark := dicttypeFields[4].Descriptor()
	// dicttype.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	dicttype.RemarkValidator = dicttypeDescRemark.Validators[0].(func(string) error)
	// dicttypeDescCreatedAt is the schema descriptor for created_at field.
	dicttypeDescCreatedAt := dicttypeFields[5].Descriptor()
	// dicttype.DefaultCreatedAt holds the default value on creation for the created_at field.
	dicttype.DefaultCreatedAt = dicttypeDescCreatedAt.Default.(func() time.Time)
	// dicttypeDescUpdatedAt is the schema descriptor for updated_at field.
	dicttypeDescUpdatedAt := dicttypeFields[6].Descriptor()
	// dicttype.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dicttype.DefaultUpdatedAt = dicttypeDescUpdatedAt.Default.(func() time.Time)
	// dicttype.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dicttype.UpdateDefaultUpdatedAt = dicttypeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dicttypeDescID is the schema descriptor for id field.
	dicttypeDescID := dicttypeFields[0].Descriptor()
	// dicttype.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dicttype.IDValidator = dicttypeDescID.Validators[0].(func(string) error)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescParentID is the schema descriptor for parent_id field.
	permissionDescParentID := permissionFields[1].Descriptor()
	// permission.DefaultParentID holds the default value on creation for the parent_id field.
	permission.DefaultParentID = permissionDescParentID.Default.(string)
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[2].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescCode is the schema descriptor for code field.
	permissionDescCode := permissionFields[3].Descriptor()
	// permission.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	permission.CodeValidator = func() func(string) error {
		validators := permissionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[4].Descriptor()
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescPath is the schema descriptor for path field.
	permissionDescPath := permissionFields[5].Descriptor()
	// permission.DefaultPath holds the default value on creation for the path field.
	permission.DefaultPath = permissionDescPath.Default.(string)
	// permission.PathValidator is a validator for the "path" field. It is called by the builders before save.
	permission.PathValidator = permissionDescPath.Validators[0].(func(string) error)
	// permissionDescIcon is the schema descriptor for icon field.
	permissionDescIcon := permissionFields[6].Descriptor()
	// permission.DefaultIcon holds the default value on creation for the icon field.
	permission.DefaultIcon = permissionDescIcon.Default.(string)
	// permission.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	permission.IconValidator = permissionDescIcon.Validators[0].(func(string) error)
	// permissionDescURL is the schema descriptor for url field.
	permissionDescURL := permissionFields[9].Descriptor()
	// permission.DefaultURL holds the default value on creation for the url field.
	permission.DefaultURL = permissionDescURL.Default.(string)
	// permission.URLValidator is a validator for the "url" field. It is called by the builders before save.
	permission.URLValidator = permissionDescURL.Validators[0].(func(string) error)
	// permissionDescComponent is the schema descriptor for component field.
	permissionDescComponent := permissionFields[10].Descriptor()
	// permission.DefaultComponent holds the default value on creation for the component field.
	permission.DefaultComponent = permissionDescComponent.Default.(string)
	// permission.ComponentValidator is a validator for the "component" field. It is called by the builders before save.
	permission.ComponentValidator = permissionDescComponent.Validators[0].(func(string) error)
	// permissionDescWeight is the schema descriptor for weight field.
	permissionDescWeight := permissionFields[11].Descriptor()
	// permission.DefaultWeight holds the default value on creation for the weight field.
	permission.DefaultWeight = permissionDescWeight.Default.(int)
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[13].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[14].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionFields[0].Descriptor()
	// permission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	permission.IDValidator = permissionDescID.Validators[0].(func(string) error)
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescName is the schema descriptor for name field.
	positionDescName := positionFields[1].Descriptor()
	// position.NameValidator is a validator for the "name" field. It is called by the builders before save.
	position.NameValidator = func() func(string) error {
		validators := positionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// positionDescCode is the schema descriptor for code field.
	positionDescCode := positionFields[2].Descriptor()
	// position.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	position.CodeValidator = func() func(string) error {
		validators := positionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// positionDescWeight is the schema descriptor for weight field.
	positionDescWeight := positionFields[3].Descriptor()
	// position.DefaultWeight holds the default value on creation for the weight field.
	position.DefaultWeight = positionDescWeight.Default.(int)
	// positionDescRemark is the schema descriptor for remark field.
	positionDescRemark := positionFields[5].Descriptor()
	// position.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	position.RemarkValidator = positionDescRemark.Validators[0].(func(string) error)
	// positionDescCreatedAt is the schema descriptor for created_at field.
	positionDescCreatedAt := positionFields[6].Descriptor()
	// position.DefaultCreatedAt holds the default value on creation for the created_at field.
	position.DefaultCreatedAt = positionDescCreatedAt.Default.(func() time.Time)
	// positionDescUpdatedAt is the schema descriptor for updated_at field.
	positionDescUpdatedAt := positionFields[7].Descriptor()
	// position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	position.DefaultUpdatedAt = positionDescUpdatedAt.Default.(func() time.Time)
	// position.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	position.UpdateDefaultUpdatedAt = positionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionFields[0].Descriptor()
	// position.IDValidator is a validator for the "id" field. It is called by the builders before save.
	position.IDValidator = positionDescID.Validators[0].(func(string) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[2].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[3].Descriptor()
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[4].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[5].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(string) error)
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescRoleID is the schema descriptor for role_id field.
	rolepermissionDescRoleID := rolepermissionFields[1].Descriptor()
	// rolepermission.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	rolepermission.RoleIDValidator = rolepermissionDescRoleID.Validators[0].(func(string) error)
	// rolepermissionDescPermissionID is the schema descriptor for permission_id field.
	rolepermissionDescPermissionID := rolepermissionFields[2].Descriptor()
	// rolepermission.PermissionIDValidator is a validator for the "permission_id" field. It is called by the builders before save.
	rolepermission.PermissionIDValidator = rolepermissionDescPermissionID.Validators[0].(func(string) error)
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionFields[3].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() time.Time)
	// rolepermissionDescID is the schema descriptor for id field.
	rolepermissionDescID := rolepermissionFields[0].Descriptor()
	// rolepermission.IDValidator is a validator for the "id" field. It is called by the builders before save.
	rolepermission.IDValidator = rolepermissionDescID.Validators[0].(func(string) error)
}
