syntax = "proto3";

package admin.service.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "organization/service/v1/organization.proto";
import "organization/service/v1/position.proto";

service Organization {
  // 列表的tree
  rpc OrganizationTree(organization.service.v1.OrganizationTreeRequest) returns (organization.service.v1.OrganizationTreeResponse) {
    option (google.api.http) = {get: "/admin/v1/organization/tree"};
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "组织-Tree"
      description: "获取组织树"
    };
  }
  // 创建
  rpc CreateOrganization(organization.service.v1.CreateOrganizationRequest) returns (organization.service.v1.Organization) {
    option (google.api.http) = {
      post: "/admin/v1/organization"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "组织-创建"
      description: "创建组织"
    };
  }
  // 更新
  rpc UpdateOrganization(organization.service.v1.UpdateOrganizationRequest) returns (organization.service.v1.Organization) {
    option (google.api.http) = {
      put: "/admin/v1/organization/{id}"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "组织-更新"
      description: "更新组织"
    };
  }
  // 更新状态
  rpc UpdateOrganizationStatus(organization.service.v1.UpdateOrganizationStatusRequest) returns (organization.service.v1.Organization) {
    option (google.api.http) = {
      put: "/admin/v1/organization/{id}/status"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "组织-更新状态"
      description: "更新组织状态"
    };
  }
  // 批量删除
  rpc DeleteOrganization(organization.service.v1.DeleteOrganizationRequset) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/admin/v1/organization"};
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "组织-删除(批量)"
      description: "删除组织(支持批量)"
    };
  }

  // 岗位模块
  // 列表
  rpc ListPosition(organization.service.v1.ListPositionRequest) returns (organization.service.v1.ListPositionResponse) {
    option (google.api.http) = {get: "/admin/v1/position"};
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-列表"
      description: "获取岗位列表"
    };
  }
  rpc GetPosition(organization.service.v1.GetPositionRequest) returns (organization.service.v1.Position) {
    option (google.api.http) = {get: "/admin/v1/position/{id}"};
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-详情"
      description: "岗位详情"
    };
  }
  // 创建
  rpc CreatePosition(organization.service.v1.CreatePositionRequest) returns (organization.service.v1.Position) {
    option (google.api.http) = {
      post: "/admin/v1/position"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-创建"
      description: "岗位创建"
    };
  }
  // 更新
  rpc UpdatePosition(organization.service.v1.UpdatePositionRequest) returns (organization.service.v1.Position) {
    option (google.api.http) = {
      put: "/admin/v1/position/{id}"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-修改"
      description: "岗位修改"
    };
  }
  // 更新状态
  rpc UpdatePositionStatus(organization.service.v1.UpdatePositionStatusRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      put: "/admin/v1/position/{id}/status"
      body: "*"
    };
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-修改状态"
      description: "修改状态"
    };
  }
  // 删除
  rpc DeletePosition(organization.service.v1.DeletePositionRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/admin/v1/position"};
    option (gnostic.openapi.v3.operation) = {
      tags: "Organization"
      summary: "岗位-删除(批量)"
      description: "岗位删除，支持批量删除"
    };
  }
}
